### ISSUE TITLE
setfattr: Operation not supported error

### ISSUE THREAD

**Issue by unai-ndz** [trapexit/mergerfs#1175]
**Describe the bug**

`setfattr` or it's variants fail with `Operation not supported` error.

**To Reproduce**

```bash
mkdir -p /mnt/test

# I tried several combinations of options but I can't get them to work
mergerfs -o security_capability=true,posix_acl=true /mnt/hdd9 /mnt/test

touch /mnt/test/test

setfattr -n security.selinux -v "system_u:object_r:etc_t:s0" /mnt/test/test
# setfattr: /mnt/test/test: Operation not supported

getfattr -h -n security.selinux /mnt/test/test
# security.selinux="system_u:object_r:fusefs_t:s0"

setfattr -n user.foo -v bar /mnt/test/test
# succeds

# However it works if run directly on the drive
setfattr -n security.selinux -v "system_u:object_r:etc_t:s0" /mnt/hdd9/test
# succeds
```

`seclabel` does not show in the mergerfs mount but it does in the original ext4 drive
```bash
cat /proc/mounts | grep /mnt/hdd9
# /dev/sdg1 /mnt/hdd9 ext4 rw,seclabel,relatime 0 0
# /mnt/hdd9 /mnt/test fuse.mergerfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
```

**System information:**

Tested on fedora 38 with: `2.33.5-1.fc36`, `2.35.1-1.fc37`, and locally built `2.35.1-1.fc38`.
Also tested on fedora 36 with `2.33.5-1.fc36`

 - OS, kernel version: `Linux Fedora 6.2.11-300.fc38.x86_64`
 - mergerfs version: `2.35.1`

**Additional context**

I noticed this while moving from `docker-compose` to `podman`.
Volumes with :z or :Z show `Error: lsetxattr /mnt/test operation not supported`
This didn't happen with docker for some reason, but as explained above is not unique to podman.

**Comment by trapexit** [comment]
As far as I know SELinux is not supported on FUSE filesystems. Until that changes there isn't much I can do besides mention that fact in the docs.

https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/CAN9vWDLGA4%3Dg3peKVWkX7gLRiVUUvJAQx9kiXHgqdeX6eh0MYA%40mail.gmail.com/#msg35284942

**Comment by unai-ndz** [comment]
Damn, you are right. 
[Here](https://bugzilla.redhat.com/show_bug.cgi?id=1272868) is the tracker for adding support into the kernel, does not look promising tbh.

I assumed it was supported as docker worked and I could read the selinux context but that's not how it works.

Fyi docker just skips setting labels in any filesystem that does not support it while podman tries anyways.

Thanks for the help and for this software, I've been using it for years and I am very happy with it.

**Comment by trapexit** [comment]
Glad it works well for you. I'll add something to the docs to make it clear it isn't supported.

**Comment by shyney7** [comment]
@trapexit @unai-ndz Im facing the same problem on Fedora Server 44 and using podman instead of docker. Labeling just gets ignored.
Is it possible to get around this by adding `,context="system_u:object_r:container_file_t:s0"` into the `/etc/fstab` options in the mergerfs row?
And then just drop all `:z` from every `Volume=` line pointing to the shared mergerfs mount in the podman quadlets? 

Would this work or are there any problems if using this "hack" ? Appreciate your thoughts on this.

btw: didint find any SELinux specific mentions on the mergerfs docs.

Red Hat Docs: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/selinux_users_and_administrators_guide/sect-security-enhanced_linux-working_with_selinux-mounting_file_systems

#### Edit:
Ok I was wondering why all my containers that mounted the mergerfs pool with the `:z` option could still access the pool and do all operations since the relabeling was not working and I still saw the `system_u:object_r:fusefs_t:s0` label on all files. 

Then I saw that Fedoras container-selinux policy may already allow container_t processes to manage fusefs_t content : https://github.com/containers/container-selinux/blob/main/container_selinux.8

>The SELinux process type container_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.
```
.B fusefs_t
```
Since I use `UserNS=keep-id` on all my containers that need access to the shared mergerfs pool the access is granted as shown by the container-selinux policy. So dropping all the `:z` from the containers that mount the mergerfs pool should be enough so a relabeling doesnt cause overhead on every container start / restart (and will fail anyway). 

@trapexit if you want I can add this info to the docs if you tell me where exactly you would want me to add this section and create a PR.

**Comment by trapexit** [comment]
Hmmm... I'm not sure. Maybe in FAQ somewhere (even an SELinux section in FAQ?) I'm open to suggestions.

**Comment by shyney7** [comment]
Ok will test this further to confirm my findings and then if everything works as intended I will create a PR. I think this would help anyone using podman on SELinux enabled systems especially when the pool gets bigger and bigger.

**Comment by trapexit** [comment]
Awesome. Appreciate it.
