### ISSUE TITLE
A rpm for Fedora 38

### ISSUE THREAD

**Issue by edgan** [trapexit/mergerfs#1177]
&nbsp;&nbsp;I just upgraded my system that I use `mergerfs` on from `Fedora 37` to `Fedora 38`. I found I was on an older rpm from before `Fedora 37`, and so I upgraded to the latest `Fedora 37` rpm. It would be nice if there was a `Fedora 38` rpm.

&nbsp;&nbsp;Even nicer would be `dnf` repositories so I could just run `dnf update` instead of having to remember to come back to `GitHub` for updates.

**Comment by trapexit** [comment]
I'm in the middle of a cross country move and my server with my build setup is in transit at the moment so there will be a delay on a dedicated 38 release. Though I'd be a little surprised if 37 failed to work or would be any different from a new one.

As for a repo. I hesitate to endorse upgrading unnecessarily. Especially since I plan on doing a big change to the software in terms of configuration that would require a new package name to keep from breaking people. If I do decide to do personal repos they would be out of date for that very reason. Bugs happen and I don't want to be inadvertently breaking people's setup.
