### ISSUE TITLE
Feature request: minfreespace option to include %

### ISSUE THREAD

**Issue by mikehunt114** [trapexit/mergerfs#170]
Would be nice to see the minfreespace option also configurable as a % of free space remaining, as available with mhddfs.

**Comment by trapexit** [comment]
I'll look into it but it seems like it could result in odd behavior. The
bigger the difference between drive sizes the worse that would behave.

**Comment by mikehunt114** [comment]
Why odd behavior?  Ex. ext4 reserves space for the super user based on a %.  I have used both configurations...I think it's just a preference.

**Comment by trapexit** [comment]
Odd in that if you have a a large drive and small drive it'd be rather different in terms of what that percentage means. 5% of a 256GB SSD is 12GB vs 5% of a 8TB HD being 400GB.

**Comment by rubylaser** [comment]
I have always disliked the reserved space on ext3/4 being in percentage.  I would much prefer the reserved space as a GB value as already exists.  This means you always have a consistent minfreespace values across all disks vs. being wildly different on differing sized disks. As stated above by @trapexit here's a realistic 5% reserved value on sizes of media disks.

8TB = 400GB
6TB = 300GB
4TB = 200GB
3TB = 150GB
2TB = 100GB
1TB = 50GB.

Well, many of those are way too much reserved space you say, so let's bump it down to 1% reserved space. And, let's pretend you have a pool of disks varying from 4TB disks down to a couple old 1TB disks.  

On the 4TB disks, you would have 40GB reserved, still a probably a little bit too much overhead wasted for things like SnapRAID's parity disk, but the 1TB disks would only have 10GB reserved, which is a little too close to being topped off for my liking. These greatly varying values are the main reason I greatly prefer the current implementation of a defined GB size of reserved space on each disk in the pool

**Comment by KillerJK** [comment]
There is a valid use case for this feature request. It would be useful if the drives were using ZFS (individual pools merged by mergerfs), because the allocator changes the algorithm from first-fit to best-fit when a mestaslab has less than 4% of free space. Best-fit is slow, and you want to avoid that situation. Openzfs wiki [recommends](http://open-zfs.org/wiki/Performance_tuning#Free_Space) keeping the free space of the pool above 10% or 5%, depending on the value of metaslab_lba_weighting_enabled. Other people say you should keep at least 20% of free space. The thing is the code itself is checking for percentages, and depending on the size of the drive, you need to keep more or less empty space.

I agree that using a percentage means more wasted space on bigger drives, and I'm not sure why zfs works this way, but it does. I dislike that behaviour, but that's how it is. At the moment, you have to set a different quota for every drive if you want to protect yourself against fragmentation. In linux, the quota is being reported correctly by df as the new size for those datasets, and I checked that mergerfs correctly uses it.

Being able to use % in minfreespace would be convenient, perhaps, but not really needed.
Actually, percentages could be a bad idea even in zfs. Because there is a fixed number of metaslabs, bigger drives have bigger metaslabs. So zfs will be modified eventually with a reduced % of free space you must keep because they suppose you are using big, modern hard drives. I think it already happened once, it used to be 20%? At home however you will probably have drives of multiple sizes all mixed together. You will want different  percentages of empty space in them, I suppose. Quotas would fix that, or different values of minfreespace for every drive.

I have no idea if btrfs needs a % like zfs, or if mergerfs can correctly detect the free space in that filesystem (I've read df reports funny numbers when used with btrfs).

**Comment by trapexit** [comment]
I don't think I follow. Minfreespace is to help keep drives from filling. The same way on ext{2,3,4} you can leave some space exclusively for root. Drives are skipped in selection for creating new files when that mark is met. Given mergerfs can move files to new drives when it runs out of space it's really just to keep that costly behavior from kicking in unnecessarily. To be set to a value between the average file size to the largest file on the drive. The layout of files on the drive should be determined by the policy and existing path layout.

**Comment by KillerJK** [comment]
What I tried to explain is that zfs, to avoid fragmentation, has two options. Setting different quotas for every drive in zfs, or using minfreespace with a %. The goal here is keeping metaslabs above 4% of free space. To do that, you need to make sure the pool is above 5% or 10% of free space. When used with mergerfs, every individual drive is a different pool, so the goal becomes making sure drives always have 10% of free space. Not a certain amount of GB, but a percentage.

If you could set minfreespace as 5% or 10%, all zfs pools would be happy, since you would never reach the point where it switches to best-fit mode and performance suffers. Mergerfs can't do that though, because minfreespace can only be a fixed value in GB used by all the drives, regardless of their size. The workaround is reserving this % with quotas in zfs. On top of that, you would of course use minfreespace to avoid the costly behaviour you just explained. It's just you would be able to do both things in mergerfs if percentages were supported. You wouldn't need quotas this way. Just minfreespace=10%.

Anyway, as I said, I can think of situations when using the same % for all the drives wouldn't be desirable even with zfs (maybe). I don't want to make this too confusing with zfs concepts that have nothing to do with mergerfs. It's no big deal, really. It's just I knew a valid use case for this feature request, and wanted to tell you. I wrote my reply to help people that came here trying to use mergerfs with zfs and were wondering how to make sure mergerfs wouldn't fill the drives above the % the documentation tells you. This is a concept that just doesn't make sense with normal filesystems, because a percentage means too much wasted space with big drives.

*This is why it minfreespace=10% would be useful in zfs (copied from openzfs wiki):
Free Space
Keep pool free space above 10% to avoid many metaslabs from reaching the 4% free space threshold to switch from first-fit to best-fit allocation strategies. When the threshold is hit, the metaslab allocator becomes very CPU intensive in an attempt to protect itself from fragmentation. This reduces IOPS, especially as more metaslabs reach the 4% threshold.

The recommendation is 10% rather than 5% because metaslabs selection considers both location and free space unless the global metaslab_lba_weighting_enabled tunable is set to 0. When that tunable is 0, ZFS will consider only free space, so the the expense of the best-fit allocator can be avoided by keeping free space above 5%. That setting should only be used on systems with pools that consist of solid state drives because it will reduce sequential IO performance on mechanical disks.
