### ISSUE TITLE
Q: what will happend if I use mv?

### ISSUE THREAD

**Issue by jkaberg** [trapexit/mergerfs#175]
I was wondering; I got a lot data (roughly 10TB) sitting in folder mergerfs/a/ mergerfs/b/ and mergerfs/c/, if I would issue an ```mv``` to for all 3 to directory mergerfs/foo/bar/d/ would that effectively be an ```cp``` or would the "paths" just get changed on every drive affected (like a normal fs/drive)?

Sorry about this, but it's a bit unclear

**Comment by trapexit** [comment]
It's described in the section on 'rename'. "mv" is a rename and on EXDEV, copies & unlinks. All cross directory renames result in EXDEV currently. Remember that "mv" is not a single thing. It's a tool which merges several behaviors low level behaviors.

The reason it works this way currently is to put responsibility of handling these situations in the app doing the rename. 

Since many apps fail to handle the situation correctly I'm changing to rename after cloning the target path. This means renames will not return EXDEV. "mv" will not fall back to copying data.

There is no good answer to "rename" behavior. A compromise could be trying to do renames for all sources found and if anything fails with ENOENT return EXDEV. Nothing is perfect. Rename by its nature does not work with the idea of the policies.

**Comment by jkaberg** [comment]
Thanks for takeing your time explaining @trapexit, it's unfortunate but I fully understand the reasoning behind it

In my rush for awnsers I somehow overlooked this https://github.com/trapexit/mergerfs#rename

Sorry about that

**Comment by jkaberg** [comment]
But if I change the directory name/path on each of the affected drives manually then it will propagate properly with mergerfs when browsing the mergerfs mount?

**Comment by trapexit** [comment]
No problem.

Yes. None of the layout is cached so any changes made to the underlying layout will be seen immediately.

BTW... what behavior are you looking for? To have them stay on their same drive or to be moved to the drive according to the policy?

**Comment by jkaberg** [comment]
Moved to the drive according to policy I guess :-)

The thing is I just wanted to change path of the files (more convenient), where they reside is less of a concern in my specific case (I don't want to waste time moving the 10TB across the disks again)

**Comment by trapexit** [comment]
At this point I think I have two options.

1. Be a little more liberal about cross directory renames. If both paths exist on the same drive then try the rename, otherwise return EXDEV and leave it to the app calling rename.
2. Never return EXDEV. Turn rename into a combination of what "mv" would do. Try to rename, if that returns EXDEV then copy the directory/files over according to the policy.

2 is safer (given some apps don't handle EXDEV as they should) but reasonably more complicated. It also can have drastically different runtimes without the app being able to handle it.

I think I'll try 1 first and see how that goes. If apps still have issues perhaps I'll try 2.

**Comment by cowai** [comment]
If I have two folders.
folder1 and folder2. Both are on the same drive.
Inside folder1 there is a 10gb file,1000mb.bin, folder2 is empty.


Why does it take ~4 seconds to move it? If cd into the actual drive and to it from there, its fast (milliseconds), but from the pool its slow.
I have the pool mounted with directio_io. With it off I get like 12-18seconds doing the same command.
```shell
root@cowai-NAS:/pool/tmp# time mv folder1/1000mb.bin folder2/

real    0m4.130s
user    0m0.012s
sys     0m0.209s

root@cowai-NAS:/pool/tmp# mergerfs -v                                                                                                                                                                                                            
mergerfs version: 2.8.0
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19
root@cowai-NAS:/pool/tmp# uname -r
3.13.0-68-generic

**Comment by trapexit** [comment]
Because the existing version treats all cross directory `rename` calls as `EXDEV` which forces `mv` to copy the data manually. I've got details in the manual. 

The next version of mergerfs I've made the rename handler more complex so that it will try to actually rename when it can but the behavior will be different depending on whether you're using a path preserving algo (`epmfs`) or not.
