### ISSUE TITLE
[Possible Enhancement] - Have mergerfs keep simple file list to allow for single disk spinups

### ISSUE THREAD

**Issue by rubylaser** [trapexit/mergerfs#214]
@trapexit, I don't know if this is possible (I read you mention it on a Reddit thread) to keep a list of the files in memory or perhaps on an external SSD so that the whole pool doesn't need to be spun up to perform a read.  

I'm thinking about a use-case like Plex or Kodi, where the application is just looking for a file to play, so mergerfs could just provide the path to the one underlying disk instead of searching the whole pool.  This could be a pretty neat way to keep almost all of the pool disks spun down most of the time.

Thanks again for your work.

**Comment by trapexit** [comment]
I've been researching the whole "should disks be spun down" and it seems like there isn't any consensus. While I understand the desire to have them spun down and am pretty practical about such things (people want it... I'll do it if it makes sense for the project) I'm not sure it's a good idea. 

It's not just the files I need to keep. It's the metadata as well. And *any* caching can massively complicate things. As an example the metadata caching native to FUSE is buggy. There are known (and probably unknown) security problems with it.

The other problem is that most ways I can think of to do this it'd impact the normal usage. Not functionally but under the covers I'd probably need special code to check just for this.

If it was just providing a listing of files it'd be far easier but needing to handle the metadata (which from the filesystem perspective is entirely separate from file listing) really screws things up. In future versions of FUSE I can do both in one command and with that I could knowingly pass back the list of files and their metadata. That'd make this much much easier.

So... I'll keep this in mind and experiment with libfuse3's readdirplus which would help simplify this but really I'll hope that SSD costs drop faster than hard drives :)

**Comment by rubylaser** [comment]
Thanks for the speedy reply. The main reason I spin down disks is strictly for the energy savings.  When all 24 of my disks are spinning, it draws a couple hundred watts.  With them all spun down, it's closer to 50-60 watts which leads to a pretty substantial cost savings in electricity (and potentially cooler needs in the summer months).  

That being said, the way it works right now is fine.  I definitely wouldn't want to encourage you to try to create something that is overly complex or could be error prone, especially if libfuse3 could potentially help with some of this in the future.

I also wish that SSDs would get cheaper. But, it's probably going to be a while before I can cost effectively match my current roughly 80TB of spinning rust disk space with SSDs.

**Comment by trapexit** [comment]
libfuse3 isn't out yet but I've been considering statically linking libfuse to deal with the fact different versions are used across different distros and it causes headache with bug reports. With a statically linked libfuse I can introduce libfuse3 without distro support and a metadata cache should be way easier.

My idea is that you'd provide a path as the cache and out of band a cache can be built. It'd collect the files for a path and the metadata and write it to a special file. It'd be placed in the same relative path as the path you wish to cache. Then when doing directory scans I can look for that file's existence and if present use that data instead of the original. For paths that don't change much this may be good enough.

My concern though is that any other random check would spin up all the drives and defeat the purpose. Such as a downloader of some sort.

**Comment by rubylaser** [comment]
This sounds great.  I would wonder in the case of the downloader, wouldn't mergerfs be aware of where the file(s) were going to be written based on the write policy and couldn't this info be used to update the cache without the need to spin the whole pool up again?

**Comment by trapexit** [comment]
Making the cache aware across all functions is difficult. I'd basically have to recreate everything the operating system does already. And libfuse does. I'd rather not put all that complexity into the product for this one usecase (which is probably a very small set of users). The whole of the platform already does it's own caching... just opportunistically. If someone wants a full, in memory, file layout and metadata cache... it should probably be it's own thing.

**Comment by trapexit** [comment]
I just investigated Plex... it opens files even when not streaming them... just going through a series. This would mean drives would spin up on casual usage. If I cached where a file was then maybe at least only that drive would need to spin up but even then any casual usage would probably hit multiple drives and any scheduled full scans would force them all to spin up too. Without controlling for a very specific app's usage this is almost impossible to do.

**Comment by mjmeehan** [comment]
Seems like fs metadata caching is best left to the component with the most
information on access patterns and tolerance for stale data. In this case,
Plex.

**Comment by mjmeehan** [comment]
...though I suppose you could register an inotify on each merged path and
keep metadata up to date actively. Depends on reader vs writer volume as to
whether it makes sense.

**Comment by trapexit** [comment]
I actually already threw together an app which would create a cache and keep it up to date via inotify. It's pretty straight forward. Walk the directory you want to cache, create files for each file found with the result of lstat in them, directories are created as directories and a special file with it's lstat is created, for faster readdir's you can create a readdir cache in another file per directory as well. Attach to attrib and unlinks with inotify and update on the fly afterwards.

In the stat callback you'd try to open the cache file with the same relative path. If not ENOENT then you read that into struct stat. Otherwise do what is done now. For readdir's do the same.

The cost is that extra open attempt all the time. Probably not a big deal. Alternatively force the user to provide cached paths and compare against that first. Less flexible though.

Again... problem is at least Plex open's files making all of this pointless unless I made it so the open policy wouldn't scan usually. It'd require caching per file source drives. And then checking the cache for every single function which would touch the file at all. It just doesn't seem like the benefits are there.

**Comment by rubylaser** [comment]
@trapexit I'm impressed you threw something like that together last night.  Again, if this doesn't make sense, don't waste your valuable time.  Thanks for doing this though. It seems like this could also be coupled with as a write caching solution (to SSD) if you wanted to extend the behavior :)

**Comment by trapexit** [comment]
I kind of want it to work but it feels like it wouldn't work like people hope. It would really vary based on usage patterns of the user and the software used. And it wouldn't be beneficial enough to the average user. It's an empirical thing given all the moving parts so I probably need to implement it to see if it'll work.

I'll keep playing and see how it turns out.

**Comment by rubylaser** [comment]
Sounds good.  If it's not worth it or is error prone, don't worry about it.  There is always the option for me in Plex, to just add the individual disks as folders and then Plex knows what is on each disk and will only spin up one vs. searching through them all.

**Comment by tgharib** [comment]
>I just investigated Plex... it opens files even when not streaming them... just going through a series. This would mean drives would spin up on casual usage.

This sounds like a bug on Plex - not on your side. Even if I wasn't using mergerfs and I was just using a single drive, Plex would constantly keep my disk spinning. I don't use Plex but I do use other software that doesn't have this bug so this feature will still be useful for non-buggy software that need to access files.

**Comment by trapexit** [comment]
It's accessing the file to get metadata or confirm it exists. There is no other way to do certain actions without actually looking at or for the file.

**Comment by rubylaser** [comment]
As @trapexit mentioned, this isn't a bug. An update or a scrape will require a disk spin up as that's the only way to verify the file and the record in the database. 

That being said, I have all of Plex's automatic library update features off (including "Update Library Periodically" and "Update Library Automatically").  I either update manually or section refresh from various clients to trigger an update.  With the auto features turned off, I can browse through a whole section or subsection, including viewing individual episodes metadata without the disk needing to be spun up. Even the metadata is stored in the database and viewing it does not result in a disk spin up until I playback / view the file.  

I am currently running Plex with each individual disk mapped as a folder to content sections (i.e. /disks/disk01/misc_videos/4k_samples and /disks/disk02/misc_videos/4k_samples make up my 4K Samples library). Although, this is more of a pain for me to manage an ensure that all of my folders are added to each section, it allows Plex to "know" exactly where each file is rather than having to scan the pool to find the file for playback.  The "search" for the file can potentially cause a few or all of the disks to spin up until it "finds" it.  

To minimize disk spinup for playback, Plex might not lend itself to pooling software unless there is some way to allow for pool to know what underlying disk a file is on and to only spin that one disk up for playback. This is why I asked about a method to for mergerfs to somehow keep this info without having to spin up the whole pool to search for a file, but as was mentioned above, this is more difficult and error prone than it is likely worth.

**Comment by tgharib** [comment]
Maybe "bug" was a poor choice of word. In my opinion, I consider it poor design on Plex's part. It should either allow me to delete the files from the Plex interface or it should only a check for deleted files manually. That would annoy me if it consistently check for deleted content and I used Plex especially since I very rarely do so. The reason why I don't think you should worry about Plex is because Plex spins up an array of drives even without mergerfs. I think the cases where mergerfs spins up all the drives but a (jbod) array of drives doesn't is what is critical: for example, reading from a single file.

**Comment by trapexit** [comment]
Worrying about spinning up disks is not generally practical for any product. You have many things accessing a single devices. Any one of those things could need to check something and it would spin up. Stat'ing of files is not an unreasonable behavior but doing so would trigger a spin up.

mergerfs is a generic merging proxy. It is non-trivial to cache all data about all files on all drives and keep it up to date. If JBOD is literally concat'ing drives together end over end then they can not spin things up because it's not needing to worry about it. It calculates the block offset and accesses the drive in that superset range. Mergerfs has to look, based on the policy, at perhaps every drive for the file you are looking for. The alternative is that at startup (or as requested) it scan all files, for all possible policies, and store the information for later. But since drives can and do get changed underneath it that data will get stale. Even if we ignore the caching problem the cost of scanning thousands to millions of files is costly in time and memory.

**Comment by trapexit** [comment]
And to be fair... outside of noise and maybe heat (which both are things that need to be accounted for anyway for worse case situations) there is very very little financial or mechanical benefit from spinning down drives.

You're looking at a few dollars a year savings and the evidence is at best uncertain as to whether spinning drives down is good, neutral, or bad.

**Comment by rubylaser** [comment]
@trapexit I completely agree, and I'll just close this issue out.  Now that you have explained why this won't work or at least work reliably without a huge cost, there are WAY more cons than pros for this.

**Comment by rubylaser** [comment]
@tgharib This doesn't pertain to mergerfs, but I'll just drop this here quickly. Plex web does allow you to delete files from the web interface and will not trigger a whole section refresh (doesn't need to spin up all disks if folders are individually mapped as I said above).  It will also only check for deletions automatically if the update automatically and periodically are enabled (they are defaults, but easily disabled via checkbox).

**Comment by trapexit** [comment]
BTW... I had created a prototype of caching data per directory but without taking into account policies. It however would require manual rebuilding of the cache or some other daemon which would update the cache. 

The problem is that drives behave different and some can be checked to see if they are spinning and some not. Some will spin up when you check their power state it appears which defeats the purpose. And I'm not entirely clear that something like inotify wouldn't interfere with a spindown.

**Comment by rubylaser** [comment]
Thank you for looking into this and trying to come up with a viable solution.  I really appreciate all of your hard work and the very rapid pace of your responses and development!

**Comment by Artiume** [comment]
It's been a couple years time, @trapexit you ever figure out something you liked?

**Comment by trapexit** [comment]
It's not practical to prevent spinup through the filesystem. If you don't want drives to spin up you should keep software from reading the drives.

**Comment by Artiume** [comment]
ha, makes sense. thanks for replying :)

**Comment by CodingGhost** [comment]
@trapexit I know this is an old problem and it was talked much about it, so I hope this has not already been asked:
 I just setup a new server with mergerfs and noticed that when I want to access a given file, mergerfs accesses one disk after another according to ff policy to find the file. This causes massive delays in file access, as in the worst case, all 10 disks have to spin up one after another until my directory even lists. And then I have 10 spun up disks instead of only one.
what if mergerfs just kept a very simple database that stores where each file lives, just to know what drive to access. there would be no metadata involved, as it just spins up the according disk and pulls the real metadata, but only one disk will spin up instead of all in the worst case?
could be Im overlooking something here, but thats just an idea I just had.

**Comment by trapexit** [comment]
This is already discussed in the docs: https://trapexit.github.io/mergerfs/latest/faq/limit_drive_spinup/

Of course something like that is possible but as I explain in the docs there are issues and limitations with it. RAM concerns, the fact it would have to be added to basically 100% of all calls which is very invasive, to deal with out of band changes fanotify would be required but there is no way to filter events so 100% of mergerfs events would also have to be collected by the daemon watching for changes which would be pretty costly.

**Comment by trapexit** [comment]
@CodingGhost keep in mind too that *every* different function of a filesystem is doing its own thing and without knowing **EXACTLY** what is happening in your situation I can't even say if any particular strategy would help. For instance: mergerfs already has concurrent readdir which can help in your case if the request was readdir. But it could also be lots of other things. And while other functions can be made concurrent... concurrency comes with additional overhead. You would need to strace mergerfs while this situation is happening for me to comment further.
