### ISSUE TITLE
File copy errors

### ISSUE THREAD

**Issue by phatdawg** [trapexit/mergerfs#253]
I am having some difficulties, I have set up a VM with 5 20GB drives and a boot drive. I have followed the instructions on how to set up Snapraid, then the Mergerfs setup. The pool is set up correctly and I can see it over my Samba share.

My fstab
/mnt/data/* /mnt/pool fuse.mergerfs category.create=eplfs,defaults,allow_other,minfreespace=1G,fsname=mergerfsPool 0 00

df -h
Filesystem Size Used Avail Use% Mounted on
udev 986M 0 986M 0% /dev
tmpfs 201M 5.2M 195M 3% /run
/dev/sda1 7.8G 2.3G 5.1G 32% /
tmpfs 1001M 0 1001M 0% /dev/shm
tmpfs 5.0M 0 5.0M 0% /run/lock
tmpfs 1001M 0 1001M 0% /sys/fs/cgroup
mergerfsPool 80G 33G 43G 44% /mnt/pool
/dev/sdc1 20G 18G 902M 96% /mnt/data/disk2
/dev/sdb1 20G 46M 19G 1% /mnt/data/disk1
/dev/sdd1 20G 15G 4.4G 78% /mnt/data/disk3
/dev/sdf1 20G 18G 1.9G 91% /mnt/parity/disk5
/dev/sde1 20G 44M 19G 1% /mnt/data/disk4
tmpfs 201M 0 201M 0% /run/user/1000

files copy fine to the Samba share, but when the drive is running low on space it will fill up to 100% then stop. about 30sec later Windows will give a error trying to copy file message and ask to retry, If I hit Retry it will then tell me that the file exists and do I want to overwrite. when I select overwrite the file will try to copy again, I then notice that the file on the server has moved to the drive with the correct amout of free space and completes successfully.

I would assume that it would check to see if the free space exists before it started copying the file, But it appears that it does not.

I have also tried to copy direct from the CLI, it looks like the same thing happens where it will fill up the drive to 100% but the file will then move to the correct drive with the free space necessary.

I have set the xattr user.mergerfs.moveonenospc true ./.mergerfs,  If this is set to false, windows will fail the copy saying there is not enough free space, when i hit retry if will try to copy to the same drive again and fail. this will repeat over and over.

**Comment by phatdawg** [comment]
/mnt/pool# xattr -l ./.mergerfs
user.mergerfs.srcmounts: /mnt/data/disk1:/mnt/data/disk2:/mnt/data/disk3:/mnt/data/disk4
user.mergerfs.minfreespace: 1073741824
user.mergerfs.moveonenospc: true
user.mergerfs.policies: all,eplfs,epmfs,erofs,ff,lfs,mfs,newest,rand
user.mergerfs.version: 2.12.2
user.mergerfs.pid: 388
user.mergerfs.category.action: all
user.mergerfs.category.create: eplfs
user.mergerfs.category.search: ff
user.mergerfs.func.access: ff
user.mergerfs.func.chmod: all
user.mergerfs.func.chown: all
user.mergerfs.func.create: eplfs
user.mergerfs.func.getattr: ff
user.mergerfs.func.getxattr: ff
user.mergerfs.func.link: all
user.mergerfs.func.listxattr: ff
user.mergerfs.func.mkdir: eplfs
user.mergerfs.func.mknod: eplfs
user.mergerfs.func.open: ff
user.mergerfs.func.readlink: ff
user.mergerfs.func.removexattr: all
user.mergerfs.func.rename: all
user.mergerfs.func.rmdir: all
user.mergerfs.func.setxattr: all
user.mergerfs.func.symlink: eplfs
user.mergerfs.func.truncate: all
user.mergerfs.func.unlink: all
user.mergerfs.func.utimens: all

**Comment by trapexit** [comment]
Without exact information about the setup and the precise errors I can't really help.

You can't conflate high level actions like "copy" with what POSIX filesystem APIs. There is no "copy." It's "create a new file, open the old file, copy batches of data between them, close both". Minfreespace forces the create to skip drives with less than that value free. eplfs means pick the drive with least space that happens to have the directory in question.

So... of course with moveonenospc turned off it will fail. It ran the algo you asked... picked a drive... and it's too small. That's it. With it enabled it will try to copy the file to a new drive with sufficient space but could also fail. It's a complex situation. You are adding more complexity because of Samba/CIFS. I've no idea what it's doing. 

If you think it's a bug and not working as described in the documentation then please provide specifics about the layout of directories and whatnot and replicate it without Samba.

**Comment by trapexit** [comment]
And if the file is already half written... then it's not a create. It's an open. "Overwrite" is probably not "remove and recreate". It's open and overwrite. Meaning the drive already hosting that file will be used.

**Comment by phatdawg** [comment]
I have a feeling that Windows is not giving mergerfs enough time to move the file to a drive with the correct amount of space.  

basically i am copying a 6gb file from my desktop to a shared samba directory in the pool.  Then renaming the file on my desktop and copying the same file again to the shared samba directory. I do this just as a test to fill the drive to see what happens when a drive gets filled.  I am doing this on a test server that i set up in a VM to see if Mergerfs will work for me.  

I guess that because eplfs finds that there is more that the 1GB minfreespace (4gb free) it will always try and copy the 6GB file to that drive first.

I have tried without Samba and it does work as expected. I monitor the free drive space, I see the drive fill up then I see another drive start to fill and the first drive releases the space that was taken up by the transfer.

Is there other information that i can give you as to my setup?  If this is a limitation i can understand.

**Comment by trapexit** [comment]
Yes, it will always pick that drive because it doesn't know how much data you will be writing. I just see "create", a bunch of reads and writes, and then some closes. The size of the file isn't something I know up front. That's why minfreespace needs to exist to help minimize the issue + the copying on full drive.

If it works as expected without Windows/Samba I'm not sure what to suggest. What *exactly* is the error? Is the Windows client complaining about a timeout? Have you tried a similar test with smbclient on Linux? If it's a client transfer timeout I've no idea if Windows lets you change that. Have you tried making it a drive and using `copy` on the command line or something to see if it behaves the same?

You can either make the minfreespace larger or try a different policy so it's less likely to pick a disk nearly full. Otherwise, if it's a timeout, there is nothing I can do. It's not mergerfs. It's the Windows Explorer or whatever complaining that it hasn't seen any response in a while.
