### ISSUE TITLE
mergerfs over bcache - will fast rw operations be limited?

### ISSUE THREAD

**Issue by lockheed** [trapexit/mergerfs#302]
I am planning to use bcache devices in my NAS, so that fast SSD can speedup read/write performance of my pool up to 500MB/s.
Can you tell me whether using mergerfs over such a setup would introduce significant transfer speed reductions? 
If so, by how much?
Does it also degrade random, non-sequential r/w operations?
What type of CPU overheads from mergerfs could I expect?

In any case - much appreciation for your work. Even if it won't fit my use case, I think it is superb.

**Comment by trapexit** [comment]
It's best to simply try it out and see.

**Comment by lockheed** [comment]
Well, I did. 
bcache array consists of backing device (hdd) and caching device (ssd) presented to the system as one single device /dev/bcache0 (and bcache1 etc.). This device is being mounted to /mnt/test/u1 (and u2 and etc.).
Mountpoints in /mnt/test/* are compounded by mergerfs into /mnt/storage.
When writing to /mnt/storage, it looks like mergerfs is completely ignoring the caching device, reaching speed only at the level of non-cached device (35mb/s), while writing directly to /mnt/test/u1 reaches full SSD speed.
I don't think this is a speed limit of mergerfs, because that value is the same as HDD max write speed. It looks like mergerfs ignores bcache cache device. This seems strange to me, because a bcache device is presented as single block device and mergerfs should not be able to differentiate between caching and backing component of that block device.
Can you comment?

**Comment by trapexit** [comment]
I really can't comment on bcache as I've no experience with it but mergerfs is just another userland app and works like any other with regard to reading and writing from the underlying drives. If the speeds to the underlying paths is significantly different from through mergerfs (try just a single drive rather than all in the pool) then it must be mergerfs. However, on modern kernels and properly configured mergerfs can push near peak of most drives.

**Comment by trapexit** [comment]
Any updates?
