### ISSUE TITLE
force folder to not span over disks

### ISSUE THREAD

**Issue by henfri** [trapexit/mergerfs#346]
Hello,

first let me thank you for your work on mergerfs!
I am trying to use mergerfs with rsnapshot. In fact this worked fine until my disks got quite crowded.
Now, rsnapshot fails distributing files across discs (hardlinks across filesystems not being possible).

Is it possible to overcome this? 
If not maybe this is worth adding a feature. I.e. by adding a file .mergerfs_do_not_distribute into the folder one could tell mergerfs to keep the folder together.

I am aware, that I can just access the source drive rather than the mergerfs pool. But I'd like to avoid direct access to the underlying drives.

Regards,
Hendrik

**Comment by trapexit** [comment]
I'm not really sure I understand the situation. What do you by distribute? MergerFS will clone directories only if you inform it to or there is no longer a choice due to the conditions. The difference between the path preserving policies and non-path preserving.

As the docs explain if you use path preserving then link will fail sometimes with EXDEV if the path is not available on the drive the source file is and the create policy wouldn't end up on.

If you want link to always succeed you should turn off path preserving and allow mergerfs to create cloned paths on any drive as necessary. While I could... I really don't want to get into the business of creating per directory policies.

**Comment by ryecoaaron** [comment]
Is it possible to have mergerfs not select a different disk when something like rsnapshot is creating a hard link?

**Comment by henfri** [comment]
Hello,

thanks for your reply.
By distribute I mean that files in a folder end up on different drives. I understand, that this is sometimes not avoidable.

If I understand correctly, in order to turn off path preserving, I need to avoid all of these policies:
epff, eplfs, eplus, and epmf
Right?

What do you mean by "to create cloned paths on any drive as necessary"?

And I think I like Aarons suggestion: Why don't hardlinks *always* end up on the same drive/filesystem as the source of the hardlink?

Regards,
Hendrik

**Comment by trapexit** [comment]
There is only one way for mergerfs to know who the caller is when something calls "link" and it's not pretty. Even then it'd just be a guess. From it's perspective it simply gets a command "link at path A to path B".

**Comment by trapexit** [comment]
> If I understand correctly, in order to turn off path preserving, I need to avoid all of these policies:
> epff, eplfs, eplus, and epmf
> Right?

Correct. Please read the descriptions of the [policies](https://github.com/trapexit/mergerfs#policy-descriptions). "ep" in the policies means "existing path".

> And I think I like Aarons suggestion: Why don't hardlinks always end up on the same drive/filesystem as the source of the hardlink?

Because it's perfectly legit to not want that. That's the point of path preserving policies and the behavior as described in the docs. EXDEV is a valid error and a well written app must handle it. Some people don't want directories arbitrarily created on their drives. If you don't care about paths being cloned across drives don't use path preservation policies.

**Comment by trapexit** [comment]
> What do you mean by "to create cloned paths on any drive as necessary"?

It will clone the path from the source drive to the destination drive. Just like `cp -ar` would.

**Comment by ryecoaaron** [comment]
I can confirm that using "most free space" seems to fix the issue.

**Comment by dumblob** [comment]
I'm new to mergerfs and I like what I found in the doc so far. But this "spanning over disks" is something which needs more attention IMHO.

How does it behave if I set `minfreespace=98G`, have two physical disks (one almost full with 3GByte left free space and the second has 96GByte left free space), both merged with mergerfs and I start writing a 100GByte file. Will it first write either 96GByte (or 3GByte depending on mergerfs configuration) and then all of a sudden throw an error about missing space and delete the corrupted (unfinished) file?

Or will it take a look at the whole size of the file to be written (let's assume it's not a stream/pipe) and immediately fail with a descriptive error, that there won't be enough space?

Or will it not error at all and just write those 96GByte (or 3GByte) and leave a corrupted (i.e. incomplete) file there?

Or how will it behave?

Could this edge case be meticulously documented?

**Comment by trapexit** [comment]
I don't know what you mean. There is no "spanning over disks" feature.

>How does it behave if I set minfreespace=98G, have two physical disks (one almost full with 3GByte left free space and the second has 96GByte left free space), both merged with mergerfs and I start writing a 100GByte file. Will it first write either 96GByte (or 3GByte depending on mergerfs configuration) and then all of a sudden throw an error about missing space and delete the corrupted (unfinished) file?

Exactly as described. You have minfreespace=98G and two branches below minfreespace. So it returns ENOSPC as described.

>Or will it take a look at the whole size of the file to be written

That's not a thing. There is no such thing in Unix filesystem APIs. 

>Or will it not error at all and just write those 96GByte (or 3GByte) and leave a corrupted (i.e. incomplete) file there?

You have two drives that are filtered out due to minfreespace. The creation never happens. If you write to an existing file it will write till it runs out of space like any other filesystem.

>Could this edge case be meticulously documented?

It's not an edge case. It's a basic feature of the software and documented fully.

**Comment by trapexit** [comment]
It doesn't change anything. The create happens based on your create policy and when the filesystem runs out of space it will return ENOSPC.

**Comment by dumblob** [comment]
Ok, thanks for clarification!

And one additional question - could `minfreespace` be changed in runtime and if so, is it instantaneous (matter of milliseconds) or rather seconds/minutes (assuming tens of terabytes of data merged from say 6 physical SATA disks)?

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#runtime-config Use the xattr interface.

Instant

**Comment by dumblob** [comment]
> https://github.com/trapexit/mergerfs#runtime-config Use the xattr interface.

Hm, it says `NOTE: this interface will be removed in mergerfs 3.0`. How much afraid shall I be that the `xattr` shell interface will stop working soon?

And btw. what's the package name which provides the `xattr` binary? I have just `attr` on my test machine.

> Instant

Perfect!

**Comment by trapexit** [comment]
Yes, It will be removed in mergerfs 3.0. Which will be a major, backwards incompatible version as mergerfs uses semantic versioning.

On what OS? I don't know. xattr is just an example. You can use getfattr and related tooling as well.

**Comment by dumblob** [comment]
> I don't know when it will be released as I still have a lot of work to do on it

Any roadmap? I couldn't find any git branch nor any related issues nor PRs... nothing :open_mouth:. Why a major release? Any fundamental "flaws"?

(you don't have to spend your precious time answering all these questions thoroughly here if they're already answered somewhere else - perhaps in your blog posts or whatever - just point me there and that's it :wink:)
