### ISSUE TITLE
Modify time of mount not reflecting most recent change of mount contents

### ISSUE THREAD

**Issue by gene1wood** [trapexit/mergerfs#375]
Firstly, this may be a behavior of mounts in general or FUSE mounts and not an issue with mergerfs, I'm not sure. I could also just be misunderstanding what's going on.

When you create a new file in a normal (non mergerfs) directory, the modify time of the directory containing the new file is updated at the time the file is created to reflect the time that the that file was created. This is also true when files are deleted.

With a mergerfs mount, the modify time of the mount does not reflect the time of the most recent file deletion or creation but instead the time that the mount was created.

This results in an interesting directory listing that looks like this where `.` is not at the top

```
$ ls -alt
total 71142352
-rw-rw-r--.   1 user user 8441438619 Feb 12 22:46 file1.mkv
drwxrwsr-x.   3 user user       4096 Feb  9 19:10 directory7
drwxrwsr-x.   3 user user       4096 Feb  1 15:17 directory6
drwxrwsr-x.   2 user user       4096 Jan 18 12:04 directory5
drwxrwsr-x.   2 user user       4096 Jan 18 11:33 directory4
drwxr-xr-x.   5 root root         57 Jan  4 13:38 ..
drwxrwsr-x. 339 root user      28672 Dec 29 21:01 .
-rw-rw-r--.   1 user user 3204940334 Dec 24 14:24 file2.mkv
drwxrwsr-x.   2 user user       4096 Dec 23 20:31 directory2
drwxrwsr-x.   2 user user       4096 Dec 16 13:35 directory1
```

Is this how mounts work? Is this how FUSE mounts work? If not is this a bug? If not is there a setting to make a mergerfs mount behave more like a normal directory in regards to the modify time?

I encountered this problem using [Subsonic](http://www.subsonic.org/), a media streamer and jukebox. It uses directory modification times to determine when scanning for media if it should look into that directory or not.

**Comment by trapexit** [comment]
`Is this how mounts work?`: No
`Is this how FUSE mounts work?`: No
`If not is this a bug?`: No
`If not is there a setting to make a mergerfs mount behave more like a normal directory in regards to the modify time?`: Yes, please read the documentation on policies and the tips. 

https://github.com/trapexit/mergerfs#functions--policies--categories
https://github.com/trapexit/mergerfs#tips--notes

```
Kodi and Plex can use directory mtime to more efficiently determine whether to scan for new content rather than simply performing a full scan. If using the current default getattr policy of ff its possible Kodi will miss an update on account of it returning the first directory found's stat info and its a later directory on another mount which had the mtime recently updated. To fix this you will want to set func.getattr=newest. 
```

I'll try to add a bullet point to more explicitly point this fact out but it should be expected given the description of policies and their function. If you're returning the info on the first directory found it may not be the directory last updated. The reason it's the default is because the alternative is to scan all drives which is more expensive and may force them all to spin up.

**Comment by gene1wood** [comment]
@trapexit Doh! Sorry, I somehow didn't find that tip section that specifically calls out Subsonic as something affected by this. I've added the `func.getattr=newest` argument and everything works as expected now. Thank you for the pointer and apologies for an RTFM question =)

**Comment by trapexit** [comment]
No problem. I added Subsoonic to the list today so its easier to search for and also put it in the "Known issues" area as well as tips.
