### ISSUE TITLE
Feature Request , Path preserving By Date 

### ISSUE THREAD

**Issue by MasterCATZ** [trapexit/mergerfs#406]
It would be nice if the policies could be setup to use the currently used drive 
before moving onto looking for drive's with / least / most data space available for new content to me added 

I normally try and have 4 Drives that contain the newest content and expand as they get full 

Movies / Music / TV Serries / Anime 

so I can keep track of what's next to watch,
 limit the number of drives that spin up when doing file storage/searches etc 

I also try and reserve a lot of free space on pre-existing Drives for Ongoing Content, so I can keep everything organized on the same drive without Trilogies / Serries been scattered across multiple Drives 

also is it possible to configure what drives are used for 
epmfs (Movies )  eplfs  (Music)  based on a path ? 

or would I be best to create separate pools for each Multimedia Content? 
(not the most economical way for configuring redundancy )

**Comment by trapexit** [comment]
What's "the currently used drive"? All calls are independent from one another outside the opening or creating of a file and any usages of it... in which case the state is preserved.

> also is it possible to configure what drives are used for epmfs (Movies ) eplfs (Music) based on a path ?
You mean have different policies based on the path? No, there isn't. It could get extremely complicated having such a system since it'd need to allow all commands arbitrary path options. It's a very niche usecase. You could just as well create multiple pools and then have a single directory in which you symlink to those pools. It doesn't sound like you'd be having mixed policies based on multilevel deep paths.

I don't understand your comment on redundancy. mergerfs provides no redundancy features whatsoever.

**Comment by MasterCATZ** [comment]
Thanks for the reply 
I am currently using Snapraid 

Snapraid only does an RO pool using symlinks
 ( which is nice because I can do file searches with 0 drives needing to spin up ) 
so was giving mergerfs a go for creating RW pool 's

I normally put new data on the last fresh drive installed, ( ie completed series )
 so that my older drives stay spinned down for archiving etc 
 
 it would be nice if mergerfs could put the data on the drive that has the most recent uses 
that are in the same folder path 
( so Movies, Anime, Music still go to their own Drives via their folder paths ) 

however, there are other shows that have been going on for a couple of decades now which need to go to their own drives, sadly currently mergerfs is filling up these older drives that I had space reserved for these ongoing shows  

it no real drama I can always just manually put these shows on their own drives it's just a pain remembering what drive holds what shows 

is it possible to create a pool from folder paths? 

ie) most of the Drives have either Anime or Movie Folders on them 

currently, in my fstab I use 

/mnt/SnapRaidDrives/* /SnapRaidRW fuse.mergerfs ...

and mounted for SnapRaid to use with 

LABEL=Raid-F.HDD1.DRU1 /mnt/SnapRaidDrives/Raid-F.HDD1.DRU1 ...
LABEL=Raid-F.HDD20.DRU20 /mnt/SnapRaidDrives/Raid-F.HDD20.DRU20 ...

from what I can gather pooling using folder path would it be something like this

`/mnt/SnapRaidDrives/Raid-F.HDD1.DRU1/Movies:/mnt/SnapRaidDrives/Raid-F.HDD2.DRU2/Movies:/mnt/SnapRaidDrives/Raid-F.HDD2.DRU2/Movies /SnapRaidMoviesPool fuse.mergerfs comment=x-gvfs-show,defaults,allow_other,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=20G,fsname=SnapRaidMoviesPool 0 0`

`/mnt/SnapRaidDrives/Raid-F.HDD1.DRU1/Anime:/mnt/SnapRaidDrives/Raid-F.HDD2.DRU2/Anime:/mnt/SnapRaidDrives/Raid-F.HDD2.DRU2/Anime /SnapRaidAnimePool fuse.mergerfs comment=x-gvfs-show,defaults,allow_other,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=20G,fsname=SnapRaidAnimePool 0 0`

 or could there be a simple way for it to do all drives mounted in the SnapRaidDrives folder and for it to search for the Movies prefix in the next Directory depth?

**Comment by trapexit** [comment]
I still don't really follow. How does 'epff' not provide that should you create the base directory (Movies) on the new drive and then put it at the beginning of the list? 

Regex is not supported. Just globbing as the docs indicate. If you want all drives with a subdirectory then you need to use the correct globs. '/mnt/SnapRaidDrives/*DRU*/Anime' or whatnot.

As for 'newest'... Why would it be oldest? mtime starts at zero which is the beginning of Unix epoch. The larger the mtime the more recent the modification.

**Comment by MasterCATZ** [comment]
'epff' wouldn't this mean I have to add the drive to the beginning of list manually each time expanded? 

I gave  'newest' a go it sort of worked, 
until it randomly switched to using an old drive after an ongoing series was written to it  
is it possible to mix some policies I feel a combination of 'epmfs':'newest' would do it 

got a paypal or bitcoin wallet?

**Comment by trapexit** [comment]
Yes, the order matters. So it would require placing the drive you want to be evaluated first, first in the list. You could just name them such that it got picked up that way (since it sorts them). I don't know how else you'd determine that order. There isn't a way to know "what's the last drive used." That's not a thing. Path preservation is the feature that gives you per drive consideration based on the path. The only thing needed is to make sure the base paths are in place so it will consider them. Make sure "TV" is on every drive and then when a directory '/TV/foo' is created it will be on one drive and only that drive will get those episodes. But if you care about what drive you have to use the policy of your choice. epff, epmfs, etc.

It didn't "randomly" switch. It used the directory with the most recent timestamp. I don't understand what you mean by combination. newest and most free space only could be combined if there was a tie. 

Look at the [Support section](https://github.com/trapexit/mergerfs#support) of the mergerfs docs.

**Comment by trapexit** [comment]
Do you have a solution or do you feel there is still more which could be done?

**Comment by MasterCATZ** [comment]
it's still constantly going to an old drive, I'll work it out one day 

sorry for the delay been busy getting nyaa clone functional as the owner deleted the site a few days ago 

the issue is when it uses a recent time stamp for something that was placed on an old drive 
because the rule of the file going to its own existing folder, 
then all the newer created stuff then wants to start on that old drive

**Comment by trapexit** [comment]
Yes, because the "old" drive was updated. So it had the most recent timestamp. 

Do you have a metric which could be used to do what you want?
