### ISSUE TITLE
FR: hard_minfreespace: Don't allow creating new files when minfreespace is exceeded on all source mounts

### ISSUE THREAD

**Issue by EBNull** [trapexit/mergerfs#413]
Hi,

I've been using mergerfs on a very underpowered NAS device whose source mounts are formatted as btrfs. Because of the low power of the device writing to a nearly-filled mergerfs path causes the device to slow down, lock up, etc.

In looking into it I realized that mergerfs appeared to not be respecting the minfreespace setting, but then I realized that mfs doesn't check for minfreespace and ff has a fallback to the first option. Instead mergerfs seems to rely on the underlying filesystem to report ENOSPC which it will then bubble up to the caller (assuming moveonenospc is disabled).

In my case I essentially want to take the last (say) 4G of each source mount and pretend it doesn't exist. This would allow ample room for defragmentation and data management under the covers of mergerfs, and cause mergerfs to return ENOSPC when each source mount has less than 4G free.

I have implemented an option in my local tree (not uploaded anywhere yet) to provide this option which I call hard_minfreespace. It also adjusts the statvfs call to subtract this buffered space and now my mergerfs volume shows 0 bytes free as desired, attempting to creating a file returns ENOSPC, and the source mounts all have the reserved 4G free.

If there is interest in getting this merged upstream I can upload my pull request and perhaps productionize the feature, but if not, I'll just keep it implemented for the mfs and ff policies (which are the only ones that matter to me in this case).

**Comment by trapexit** [comment]
Does btrfs not support reserved space like ext4?

mfs doens't check minfreespace because minfreespace doesn't make sense as a filter on mfs. It's picking the drive with the most space. Given we're trying to always find space for a file and leave the rest to the actual filesystem we'd have to ultimately change the premise to do what you ask.

I don't understand why the device would slow down or lock up due to being full.

I understand the usecase but I'm not really keen on changing core behaviors. To be consistent all fallbacks would have to be removed and if all drives fail to pass the minfreespace filter then return a false ENOSPC. This would complicate the rest of the code because there are other filters which would require alternative error conditions.

Would it not be better to just have proper monitoring setup so that you can clean up when appropriate? With `moveonenospc` disabled there should be no issues with letting a drive fill. And if there is a problem it should be investigated because it shouldn't.

**Comment by EBNull** [comment]
I'm not actually aware of btrfs's full featureset (this was essentially my first foray into using the filesystem) or if it has a reserved space concept.

My create policy is actually eplus, which eventually through the fallback chain hits mfs, which is why I modified that one.

The device slowing down and locking up is obviously not the fault of mergerfs nor btrfs - it's just an underpowered device for btrfs which I seem to have discovered the hard way :).

I have added a monitoring set up but haven't gotten to alerting yet, so I just failed to notice the disks filling up.

It sounds like you're averse to adding this option which makes sense (as the core premise is leave ENOSPC handling to the underlying filesystem). Thanks for considering it, and if you change your mind let me know.

**Comment by 7eggert** [comment]
I got the same issue on a variety of locked-down arm-powered NAS (Buffalo and D-Link, using ext3/4). Each disk needs to have IIRC about 100 GB of free space unless I want it to crawl and this issue will bite me as soon as it gets a chance.

**Comment by trapexit** [comment]
AFAIK ext3/4 should not have performance issues due to space limitations. Have you ran a defrag? Using reserved storage? As I mentioned prior this isn't a mergerfs issue and I don't really want to be working around specific FS use cases.

Even if I were in support of doing so I think it's a bad idea. Why hard reject when you could set up monitoring so you can handle the situation more gracefully?

**Comment by 7eggert** [comment]
The box is completely locked down, that devices are configured using the web interface. Some of the devices don't even allow to set the file UID - any access not from UID 99 will be treated as "other" permission, so everything is world-writable for now (see feature request maybe yet to come). Stupid real world.

What's your idea of gracefully handling this issue?

As far as I see, it would have to run on EACH PC (I'm concatenating NAS) and it would just change the create policy to read-only until there is more free space anyway. Then I'd probably grab an USB disk or go shopping with money I don't have before I move the files, because currently the hardware is maxed out. Also it would either poll the disks or hook into mergerfs - maybe another fuse layer of indirection on top or below?


I already experienced the extreme slowdown on ext3/4 fs. I can't argue against my experience.

**Comment by trapexit** [comment]
What NAS are these? ext4 should only slow down (on writes) when fragmented (and space is tight). This can be true for other filesystems. Any system using them should offer some maintenance to help resolve that.

Regardless, what precisely is the concern? You don't want a degradation of quality? You want a full stop of new files being written or of future writes? Do you fill drives so quickly that even a single monitor and manual intervention is too much?

**Comment by 7eggert** [comment]
These NAS are a Buffalo TS-HTGL and a DLINK DNS-320 (according to web interface, the type plate is currently inaccessible). 

I don't want to discover the disks being too full by my systems not working - especially the ones booting from the nfs-root. (Also I want some space to be reserved for that, too.) I don't want to discover disk access being slow AND having to access the disks in order to make them fast again.

The mergerfs is an archive, automatic processes may fill it while I'm away or asleep. If I can't write to that, it's OK, I can repeat that later.

**Comment by trapexit** [comment]
Both appear to have the ability to set quotas.

I can look into returning ENOSPC when minfreespace is reached on all drives on create functions but this is a problem way beyond mergerfs and I'm not a fan of solving generic issues within the project.

**Comment by 7eggert** [comment]
Disregarding that I'd need an additional layer of a bunch of bindfs to enforce a different user for each to-be-combined directory (so per-user/group-quotas might apply):

On the D-Link one:
I'm not able to define the NFS users on the NAS in order to set individual user quotas, and nfs3 does not allow translating the UIDs.

The buffalo one:
It enforces all_squash, so any file would belong to the same quota - not even a theoretical chance to have two shares with different quotas. I don't see quotas mentioned in the UI either, even though I use the "latest" firmware from 2008. Newer models do have different firmware for different mainboards.

---

Also I didn't test yet weather it's reaching the "tune2fs -m"-limit that causes the disk lag or the lack of free blocks, I only know that a full disk is slow and that I spent two individual days of my life cleaning up the mess - that time not using mergerfs but individually moving directories out of the archive and linking files until e.g. the diskless PC booted again. Then I had a completely differend problem, searched for issues containing "slow" and found this thread describing what I'd need to avoid it, so I decided to provide insight from a user's perspective.
