### ISSUE TITLE
SSHFS mount causes "Function not implemented." when used with mgergerfs

### ISSUE THREAD

**Issue by ShapeShifter499** [trapexit/mergerfs#440]
I don't know where to start diagnosing this. I have a sshfs mount that I can read and write into just fine and 3 local hard drives which I can also read and write to. If I run the following two commands I get these kind of errors.   "mkdir: cannot create directory ‘test’: Function not implemented" 

```
sshfs -o rw,allow_other kumo@kumo.lan:/mnt /mnt/kumo-sshfs
mergerfs -o allow_other,rw /mnt/kumo-sshfs/merger_recovery:/run/media/raansu/2cf1cef1-85f7-47d2-8ce0-68987c618977:/run/media/raansu/7eb82772-fb52-4ab7-b4d8-6e1dc73636e8:/run/media/raansu/6ba521fd-ba92-4d0e-b744-132509893cd0:/mnt/recovery/ /mnt/recovery-mergerfs
```

If I omit the sshfs mounted folder I can read and write everything just fine.  Something is not right between mergerfs and sshfs but I don't know what exactly.

**Comment by trapexit** [comment]
Can you please provide me with versions of all software involved and a minimal version of the issue? IE. Does mounting sshfs alone have issues?

**Comment by jody-frankowski** [comment]
@ShapeShifter499 You should mount sshfs with `-d` or some other debug option in order to get the fuse debug information. In there we should be able to see the functions which isn't implemented.

@trapexit Just as a note, libfuse and sshfs have recently been updated, and rolling releases should already have the new version (Arch has).

**Comment by ShapeShifter499** [comment]
I'm going to close this since I no longer have the setup as described above.
