### ISSUE TITLE
MergerFS and SnapRaid losing a file

### ISSUE THREAD

**Issue by foxy82** [trapexit/mergerfs#456]
General description
===================

Hi - I'm not a user yet but came across this blog post: 

https://blog.joefallon.net/2017/07/warning-to-mergerfs-snapraid-users/

Are you able to comment on this and if it's an issue? I know there probably isn't much information to go on but would be good to understand if I need to be concerned as I was just planning to create a mergefs + snapraid server.

**Comment by trapexit** [comment]
You can check Reddit for other's comments from when this person posted that but to summarize: nothing that happened should be a surprise at all and as he points out it has nothing to do with SnapRaid or mergerfs per se. The person had a failed drive and a file was lost. Had they sync'ed before the move they'd been fine. SnapRaid is intended for largely write once read many situations. If you are expecting to use the system like a "normal" filesystem then yes... you have the same risks as a regular single drive. If you want live redundancy you have to use proper RAID (and bear the costs associated).

**Comment by hilbix** [comment]
FWIW here is my strategy on how to do it with SnapRAID with MergerFS and being safe against file losses.

First, each SnapRAID device lives in their own VG.  So SnapRAID N-redundandy means, N VG can fails.  Currently I have 3 VGs as parity groups.  This way the parity VGs can be a bit bigger than the other ones, which is needed for SnapRAID.

Second, each VG has 2 LVs, one is for SnapRAID, the other is for ZFS.

Third, the 3 VGs for parity only have 1 LV to accomodate, that they LV for SnapRAID is bigger.

Forth, the 2nd LVs form a zraid3 ZFS volume.

Fifth, all the 1st LVs are formatted with ext4 and remounted "bind,ro" into the MergerFS-Group.

MergerFS then is made of the ZFS volume for RW and all other devices for RO.

Besides of this I have a manual process which does:

- Distribute data from the ZFS to devices to the SnapRAID devices.
- Do a `snapraid sync`
- Then do a compare-remove cycle from the files on ZFS.

You can certainly improve that method with snapshots on ZFS if you like, but I didn't yet.

Note that you can also have consistent snapshots, as you can first snapshot ZFS and then, as they are RO, snapshot the (1st) LVs with LVM.

Please note that MergerFS does not CoW, which is not important for my case, as this all is used for archive storage, so files, once placed there, do not change.  There are files which change, but they are kept entirely on the ZFS side.

There is only one problem with this setup:

ZFS only allows 3 failures, while SnapRAID allows 6 failures.  For me, that is not so much a problem, as the important files are only kept on ZFS for a few days after which they are archived into SnapRAID.  So the error margin is pretty low.

However, as the ZFS partitions are small (1 TiB) compared to the big SnapRAID partitions (8 TiB), and I have so many devices, I can use mirroring on the ZFS side.  (Note that around 500 GB per drive is kept free for snapshots.)

ZFS does not allow to have zraid3 over mirrored vdevs, and the opposite is dumb, so my approach to that would be to use MD mirroring over LVM, so ZFS -> MD -> LV.

The MD is not ideal but best I can imagine.  It would be better if ZFS had the ability to add a mirror leg to a device, such that it can manage the error recovery itself, but you can come close with MD.  Also this gives you the opportunity to check the consistency of just one leg with MD, and not the need to scrub just everything.

This way scrubbing is done as follows (note: This is a plan, I never did this yet):

- Create LVM snapshot.
- Scrub ZFS (`zpool scrub`)
- Check the consistency of all MD mirrors (`cd /dev; for a in md*; do echo check > /sys/block/$a/md/sync_action; done`)
- After everything is OK (monitor `/proc/mdstat`), drop the LVM snapshot.

If errors are found on the MD level, resync the problematic leg.  You should not use the MD resync here, as this probably will fill your snapshots such that they become unusable.

Usually I will do it manually anyway, because I want to see the differences to decide myself if there is some other trouble going on, etc.  There is already too much magic going on behind the scenes, you must not lose contact to the hardware.  Luckily I am able to write such tools myself if they are needed, YMMV.  (Note that you can even do it with `cmp -l` and `dd` if you know how, so this really is not rocket science, a couple of lines of C should suffice, and you can probably use some scripting language like Python as well, even Perl could do it, even that I'd not recommend that for low level block access.)

Afterwards do a `zpool scrub` again.

Final note:  Perhaps I will probebly will not rely on LVM nor MD for mirroring.  I would go for devicemapper instead.  GenToo has some documentation on that:
