### ISSUE TITLE
MergerFS should not include free space of RO devices

### ISSUE THREAD

**Issue by hilbix** [trapexit/mergerfs#459]
General description
===================

I have a setup where only a small single device (the staging area) is RW while all others (the big fat archive drives) are RO.  MergerFS reports the combined space, not only the writeable space, because `statvfs()` on the big archive drives does return their (huge) free space.

Expected behavior
=================

MergerFS should only report the free space of the writeable devices according to the chosen create strategy.

Actual behavior
===============

MergerFS reports the free space of all devices.  This makes programs, which check for the free space, to believe there is much more free space than really available.

**Precise** steps to reproduce the behavior
===========================================

(If needed I will improve this.)

Create a MergerFS setup with 3 ext4 filesystems.

- 1 is 1 GB big.  This one is RW.  Fill this 90% with data.
- 2 are 10 GB big.  Both have mount option `bind,ro` (hence readonly) and are completely free.
- MergerFS mount options "category.create=ff,category.action=ff,category.search=ff"

Look at the free space.  It is reported more than 20 GB on free space, while really only 100 MB is free.

Now a program looking at the combined FS thinks, it can write more than 20 GB (as this is free) and perhaps starts a (slow) download (which is of unknown size, only that it is below 2 GB) and will fail in the middle, as it cannot complete (as the drive unexpectedly is full after downloading).

Think of something like `rsync` which is capable of putting pieces together by accessing already existing parts.  It really works fine with MergerFS.  So you cannot run this on the staging device alone, it needs transparent access to the already known archive.

In my case the application does not know in advance, how big the download is, so it cannot use `fallocate` to reserve the space.  Think about hundreds of such downloads happening in parallel, where the most of them are only a few kilobyte (but some might be Gigabytes taking hours).  So `fallocate` would overcommit the needed space by some factor of 50 and more which is unbearable.

When the staging area fills up, my application (actually it is a simple shell script which checks the free space and then continues if there is enough left) throttles, until the cleaner process (which archives the staging area) is able to keep up (sometimes this might take days).

I do not think such an application like mine is seldom.  What I would expect from a filesystem is, that it reports the free space which really might be written, and in the usual case underestimates the free space (see compression, deduplication and so on) in a conservative way.  However MergerFS overestimates the free space, as it counts just everything, even not writeable areas.

System information
==================
Please provide as much of the following information as possible:

* [ 2.18.0] mergerfs version: `mergerfs -V`
* [noauto,defaults,allow_other,use_ino,category.create=ff,category.action=ff,category.search=ff] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux] Linux version: `uname -a`
* [irrelevant] Versions of any additional software being used
* [too many to list here (over 100)] List of drives, filesystems, & sizes: `df -h`
* [irrelevant] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [irrelevant] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

I looked into the code on how `mergerfs` does `statvfs`, and the current one falls into the same pit.  The problematic code is in `src/statfs.cpp` because it looks like it does not ignore readonly devices.

In function `_statfs` some following pseudo-code is missing (I think) after doing the `statvfs()`:

```
if (is_readonly(srcmount[i]))
  {
    fsstat.f_bfree = 0;
    fsstat.bavail = 0;
  }
```

However I am not really sure how to create this `static int is_readonly(string srcmount)` thing .. yet.  If I happen to be able to implement it myself, I will add the patch here.  (No PR though, as I do not think I can provide it as you like it.  I just hack in what I need.)

**Comment by trapexit** [comment]
Thanks for the report. This was an oversight when I added the RO skipping. I'll fix this in the next release.

**Comment by trapexit** [comment]
On second thought... while I get what you're saying technically the existing behavior is correct. It's what's reported by readonly filesystems when statvfs is used to query them. The amount of writable storage doesn't change because it is mounted read only. It's just not accessible.

**Comment by trapexit** [comment]
There are a few different ways to have this work but as I mentioned read only drives still report their total and available sizes the same as writable so in that sense it's not incorrect behavior.

1. Do as today. Normal.
2. When read only zero out available/free. Total would still include ro drives.
3. When read only skip all together from calculation. As if they weren't there.

**Comment by YipYup** [comment]
@trapexit Making it user configurable per union member is a good idea. I may have one I want the free space reported, and another which I do not. Collectively the free space can be applied on a per-underlying mount policy and then presented collectively at the mergerfs unionized FS mount.

**Comment by EnorMOZ** [comment]
Use case: Cloud drives... We could care less what it reports back 1P, 10P,100P etc....However there could be consequences when other scripts etc look at the merged filesystem and sees there are plenty of space available when in fact local storage is full. Having it only report local storage vs cloud storage space would be ideal.

**Comment by trapexit** [comment]
Are these cloud mounts RO or RW?

**Comment by EnorMOZ** [comment]
@trapexit, Sorry very new to mergerfs. On the original mount they could be RO or RW based on the tool used.  ie: plexdrive (RO) or rclone (RO or RW). 

On the mergerfs side I currently have this `mergerfs /mnt/local:/mnt/rclone_mount /mnt/unionfs -o rw,noatime,category.create=ff,allow_other,dropcacheonclose=true,use_ino,hard_remove,auto_cache,sync_read,umask=0002,nonempty,dev,suid`

**Comment by trapexit** [comment]
I don't follow. Are you asking for RW cloud drives to be ignored when calculating storage?

RO storage is included in free space calculations by default on *nix systems. What mergerfs does is normal. What is asked for is that be changed so RO drives are not included in free space calculations.

mergerfs already ignores RO devices when creating files/directories.

**Comment by EnorMOZ** [comment]
I guess the ask would be to ignore cloud drives or make it configurable on a per union member to ignore calculating storage on that member or not.

**Comment by trapexit** [comment]
Regardless of being RO or RW? Only for calculating statfs? If its disabled for a device but the device is RW what should it do?

**Comment by EnorMOZ** [comment]
I probably have a very specific use case here. For me it would ignore the calculating statfs but still be able to RW to it.  If there is another way to accomplish this via mergerfs policy/rules please let me know. Maybe having it RW in my mount might not be the right config either. As in this case I would only want it to remove items but not particular write to it on the cloud member side.  Again I am very new to using mergerfs.  End goal though would be to only show size of the local member but not cloud. Sorry I didn't mean to hijack this issue report either. I could report this to another thread if you would prefer.

**Comment by trapexit** [comment]
It's difficult to understand the need because you're partially describing the solution rather than the problem.

Why do you want to lie to software regarding available space but have mergerfs still use the drive's space when writing?

**Comment by EnorMOZ** [comment]
Sorry ok let me describe what I am trying to accomplish.
1) I would like to be able to perform a delete against the mount in which it would remove the file from the cloud mount/member since it would not be on the local mount/member. 
2) Write to the local member/storage first.
3) Lie to software to only detect local storage space since I don't want to write to the cloud mount. ie: nzbget can detect if there is enough storage space and pause when there is not. However in the current setup it shows cloud mount available space as well so it would continue to download until the local storage is completely full and I think it would then try to upload to the cloud mount/member based on the policy. That part I am trying to avoid as well since writing to the cloud mount/member is very slow via this setup.

If you have discord or slack we can chat there in more realtime if it would help.

**Comment by trapexit** [comment]
> since I don't want to write to the cloud mount

mergerfs manages what gets written to. You're talking about *that* it gets written to in the first place.

OK... I understand the usecase. You want cloud RW so it can be interacted with casually but ignored from software using the device's size for automated create/writes. 

Ideally nzbget or whatever is using the size should be able to have a limit set rather than require a whole drive dedicated to it.

I'm not opposed to adding this but it feels like it should really exist in the software reading the size of the device. This isn't a problem unique to mergerfs.

**Comment by EnorMOZ** [comment]
Don't feel you need to make this change for my specific use case. I am ok if you said "No, to specific of a use case for mergerfs". 

Regarding nzbget it does have a stop/pause once it hits X disk usage. However because of the cloud drive it will never get to that point. Not sure if I was clear on that earlier. It would always show Peta bytes of available space.
`df -h`
`local:rclone_mount 1.1P 156T 1.1P 14% /mnt/unionfs`
`gdrive:            1.0P  155T  1.0P  14% /mnt/rclone_mount`
nzbget is pointing to `/mnt/unionfs`

In the past when I was using `unionfs with plexdrive` it would show something like  `unionfs-fuse    1.8T  341G  1.3T  21% /mnt/unionfs` which hid the plexdrive mount from file size. Not sure if it was not written to spec or what or maybe because I had plexdrive as RO on the unionfs mount..... That is why this threw me off at first.

**Comment by trapexit** [comment]
percentage is a bad metric for decision making in this case. It should offer fixed value limits. mergerfs doesn't include percentages for similar reasons.

Not sure about unionfs. If you mount a filesystem read only the free space is reported the same and read write. The space is free... you just can't use it.

If I'm going to add the OP feature I might as well make it more flexible and just allow individual opt out regardless of RO status.

**Comment by horjulf** [comment]
I guess its mostly an issue when you have `category.create=ff`, since you only create/add content on the first target, however you see free space for all targets.
Which is a bit misleading when you try to add more data and get an out of space error back when the mergerfs mount reports that free space is available.

**Comment by trapexit** [comment]
That's not how `ff` works. It's not picking the first device only. It does so based on the filtered conditions.

From the docs: 
```
Given the order of the drives, as defined at mount time or configured at runtime, act on the first one found. For create category functions it will exclude readonly drives and those with free space less than minfreespace (unless there is no other option).
```

Free space has nothing to do with the write status. A readonly drive with nothing on it will report 100% available even though 0% is usable. With quotas and similar you'll also have disconnects between reported free space and actual usable space.

**Comment by horjulf** [comment]
Would setting `minfreespace` to 0 effectively lock `ff` to the first drive ?

My use case is similar to @EnorMOZ.
2 or more drives in RW, where new files/folders are only created in the first drive and moves/renames/deletes/etc happen on all drives.

Having the possibility of locking `ff` to the first drive and reporting only its free space would help with managing the local free space.

**Comment by trapexit** [comment]
Assuming the first drive isn't RO... yes, minfreespace of 0 would effectively eliminate that check. Which means if you run out of space you'll get an "ENOSPC" error rather than that minfreespace buffer.

If you're going to go that far though why not just use the local drive straight up for the app that's writing and use the merged drive for other usage?

**Comment by horjulf** [comment]
Thanks.

In the cases where it was possible, that was the solution.
However in this case, the app needs to read from other drives in mergerfs and also write to it using the `ff` create policy.

**Comment by trapexit** [comment]
@horjulf If I add the ability to tag individual mounts similar to unionfs as `RO` or `RW` that would help your situation. I currently only skip RO drives when creating meaning if the drive was mounted RW but tagged in mergerfs as RO then you'd be able to delete but it'd be skipped for writes.

It could be argued that I should skip RO drives for `unlink` and `rmdir` as well so if I do this I might do `RO`, `RW`, and `NW` (no write)l
