### ISSUE TITLE
epmfs not respecting minfreespace of actual mount point of file

### ISSUE THREAD

**Issue by phiresky** [trapexit/mergerfs#498]
General description
===================

/vol0 is a drive with 100G free
/vol1/nfs is a drive 100G free
/vol2/nfs is a drive with 0 bytes free

mounted as `/vol0:/vol1:/vol2`

vol2 is the only drive that has path /nfs/A/ and it is full.  minfreespace is 4G (default).

I run touch /merged/nfs/A/test

Expected behavior
=================

/vol0/merged is created

Actual behavior
===============

/vol2/merged is created (or fails with ENOSPC)

I'm guessing this is because my mergerfs merges the path `/vol2` which belongs the root fs even though most of the data is in `/vol2/nfs` which is a mounted drive with no free space, and maybe mergerfs uses the free space of the root dir to get the free space, instead of the free space at the actual file path. Is this intended behaviour?

**Comment by trapexit** [comment]
The size is queried at the root path provided. It's been a long while since I wrote that but I think the reason was because I don't know if the relative directory path exists so checking the provided "root" path is best since if it fails I can safely skip it. I suppose it could try the target directory and recursively try back down to the root but that could significantly increase the cost of finding the size.

This is really mfs since epmfs is failing to find anything that matches the policy restrictions.

**Comment by phiresky** [comment]
> This is really mfs since epmfs is failing to find anything that matches the policy restrictions.

In this case, I'm actually pretty sure it is the `ep` part, since it's using the disk with the path that is existing even though it should ignore that and fall over to mfs since the existing path violates minfreespace. But I guess the problem exists for mfs drive order too and probably all other places where minfreespace is checked.

If I'm understanding it correctly, for the "ep" part it should be possible in constant time since you already checked the path exists. For the mfs part probably not.

To be precise, here: https://github.com/trapexit/mergerfs/blob/c7e93720ff3d9d5816915d910fbd82dd133e21e5/src/policy_epmfs.cpp#L96-L97

call spaceavail on `fullpath` instead of basepath. According to [statvfs(3)](http://man7.org/linux/man-pages/man3/statvfs.3.html) the call should work on any file on the drive.

If you think implementing this would cause a unacceptable perf hit or similar it should probably be mentioned in readme that all "free space" operations are based on the merge root.

**Comment by phiresky** [comment]
You could maybe even remove the call to fs::exists before that and just check the spaceavail call for `ENOENT` to avoid the syscalls walking the directory twice? I don't know enough about these things to predict if that kind of change would impact anything else.

**Comment by trapexit** [comment]
I'd need to double check but the reason for two checks is due to them behaving differently in certain error conditions.

**Comment by phiresky** [comment]
Just noticed the location I linked is wrong, my exact problem was with `create`, where the code is a bit different.

**Comment by trapexit** [comment]
I'll need to take a closer look. I think permissions can mess with statvfs in a way that required how it is now.

**Comment by trapexit** [comment]
I remember now... I use `lstat` to check existance which will not follow a symlink but check it's existence. statvfs does follow links. I need to see how the policies would differ, if at all, should they be changed to statvfs the fullpath instead of base.

**Comment by trapexit** [comment]
I've a way to address this issue for path preserving policies but I'm not sure about non-path preserving.

I emulate a no follow version of statvfs using open(NO_FOLLOW) and fstatvfs. That with the fullpath query instead of basepath will give the same kind of responses. The problem is that for non-path preserving that pattern won't work since using the full path by it's nature is the path preserving method.

I could do one of two things. Leave non-path preserving querying the base path or make it work recursively. If a path isn't found look at the parent directory. This will increase the search cost since it will no longer be a fixed number of calls but is perhaps the most correct. I doubt the increase cost would be noticed.

I could add a cache which would help a lot though now that I'd be looking at arbitrary paths it'd be a bit more complicated. Prior it'd just be a small and fixed number of paths to query and cache. Now its arbitrary. I'd need a fixed size cache to keep it from consuming too much memory. Storing the info based on the path's device ID would keep the cache size down but somewhat defeat the purpose since I'd have to query the value anyway via `stat`. While faster it's not significantly so.

**Comment by trapexit** [comment]
While trying to offer #459 I'm realizing there's just some inherent complications when trying to accommodate submounts in branches. If I allow manual tagging of branches (like /foo=RO:/bar=RW) how would it deal with someone tagging /foo=RO if there are submounts? Does it override the submount value? If not... when would it be used? Could it be used?

**Comment by phiresky** [comment]
> @phiresky could you try the "policy" branch and see if that does what you're looking for?

Sorry - I worked around this issue in my case by just rearranging my data and changing my mount roots since in the end all my data is on one disk per mount-source. It's kind of hard to reproduce since you need to create multiple virtual disks with different filling levels.

Since apparently no one else so far has had this issue it might not be worth it to change if it makes things more complicated elsewhere. It should definitely be mentioned in the readme though (free space calculations are based on the mount roots) since it's pretty hard to identify this as the issue.

**Comment by trapexit** [comment]
Of course you tell me after I've gone and rewritten a bunch of code :) 

Actually it lead me to improve some things so it was beneficial. And certainly... I'll add that to the docs.

**Comment by phiresky** [comment]
Sorry about not mentioning that earlier. Thank you for you work!
