### ISSUE TITLE
Epmfs subfolder creation on new disk

### ISSUE THREAD

**Issue by wessel145** [trapexit/mergerfs#547]
General description
===================
When a subfolder is created and the drive with the parent directory is full, i expect the policy to create the subfolder on the next drive with the most free space.

Expected behavior
=================
When copying a folder to a new subfolder on a full drive, it should create a new subfolder on the next drive so it would look like

disk 1 (3tb full)
disk 2 (2tb, empty)
disk 3 (3tb, empty)

/disk1/photoalbums/organized/A
/disk1/photoalbums/organized/B

And when moving a "C" to organized i expect:
/disk3/photoalbums/organized/C

Actual behavior
===============
`"Cannot create directory photoalbums/organized/C: no space left on device"`

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
`mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
`
* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
`/mnt/disk*     /mnt/storage     fuse.mergerfs direct_io,defaults,allow_other,category.create=epmfs,minfreespace=50G,fsname=mergerfs 0 0`
* [x] Linux version: `uname -a`
`Linux server 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* [x] Versions of any additional software being used
Not relevant
* [x] List of drives, filesystems, & sizes: `df -h`
relevant ones:

> /dev/sda1       2.8T  160G  2.6T   6% /mnt/disk3  
> /dev/sdc1       1.9T  2.1G  1.9T   1% /mnt/disk2  
> /dev/sdd1       2.8T  2.8T  4.5G 100% /mnt/parity1   
> /dev/sdb1       2.8T  2.7T   46G  99% /mnt/disk1  

I've been looking all day on forums and github, but couldn't find a solution, I want my files to stay as organized as possible on the disks (due to energy saving 🌎 ) so when i access a folder i want to spin up as less disks as possible, and my guess is that will happen when using a random policy.

Thanks in advance!

**Comment by wessel145** [comment]
MFS as policy solves the issue, but when disk 2 and 3 reach the same level it will rotate between those 2, now testing LFS as policy.

**Comment by trapexit** [comment]
You're assumption that you will spin down drives with any sort of random activity is likely incorrect. mergerfs needs to query all drives when making decisions. In my experience the OS will spin up a drive when it's queried for it's size and other metadata. Even if that were not the case the cost savings vs the added stress on the drive is not settled. A harddrive where I live costs about $0.03 a day to run 24/7. The stress on a drive in some studies can significantly reduce the life of a drive. The better solution would be to simply not include the drives until you need them. If you need the space and you have any sort of consistent usage (torrents, processing jobs, etc.) you'll rarely if ever see the drives spin down.

Regardless... why would you use `epmfs` if that's the behavior you want? There are others that would provide similar to what you ask without breaking one of the points of path preservation. `ff` would behave similarly. Filling drives in order. Or `lfs`. On any sufficiently large pool path preservation becomes difficult to sustain. If drive1 is full and you start replicating paths to drive2 then any update or addition will create further entropy in layout. Over time you will have all levels of paths on all drives.

**Comment by wessel145** [comment]
Thanks for your extensive reply. You're right, i was too eager to not switch policies. Energy is a bit more expensive here and my setup uses 8 watt spin down and 30/35 spun up. so there is a noticable difference there. My docker and other appliances run on a SSD that is outside the pool. the pool only gets accessed when needed. I'll stick with `ff` for now as my guess is that is the best policy for my needs at this moment. Maybe somehow I can cache the folder so the drives only spin up when a certain file is accessed, but that is for the future. Thanks for now!

**Comment by trapexit** [comment]
`ff` is the least likely to cause a spinup but *only* if that's the only call made by the software. (it's the only policy which doesn't need to query every drive.) If any software calls a `statfs` (df) it could cause the pool to spin up because that's what the OS will do when mergerfs calls `statfs` on all the branches.

I live in NYC... electricity certainly isn't cheap here and I'm powering 12 3.5" drives + some 2.5" so I understand the desire... but in practice, on average, it often isn't practical. If you very intermittently use the pool then perhaps but like I mentioned something as simple as a free drive space monitor can keep drives running. Best to use scratch drives in those situation if possible. For torrents that might be partials being downloaded to SSD first and then auto moved to the pool or as the docs show with caching. 

Also there is the long term costs with regard to drive life and replacement. Some studies show no impact by regularly spinning down and up drives. Others show significant impact. My experience hasn't been good with regularly spinning down drives but obviously YMMV.

This topic has been discussed a lot and I even investigated full metadata caching to limit needing to query drives for metadata and checking if there was a way for mergerfs to see if drives were spinning or not to add as part of the decision making. The former really didn't help so I never released it and as I recall the latter didn't work reliability. Checking if the drive was spun down would spin up the disk :-D

**Comment by wessel145** [comment]
Awesome, tnx. i use ff now and works as desired. I'll have to live with it the way i do now. Got my dockers setup right so they stay spun down most of the time (works really well, wrote a small script to poll the statusses every minute with hdparm into a db, hdparm -C does not spin up the drive). Anyway, some other idea passed my mind, how awesome would it be to have a script that moves stuff around on the HDD's and tries to match as many directories/subdirectories on each disk. It would probably take a long time and I'm not sure if possible, but it crossed my mind.

Thanks very much for the software

**Comment by trapexit** [comment]
It's certainly possible but as I mentioned over time I think the need to collocate becomes less practical and necessary. If you're backing up your entire pool, which most do in my experience, then you're not gaining too much. If you backup drives individually it matters even less. The only situation where it seems to be useful to keep files together is media where you're not backing anything up and you'd rather lose all of TV show X than every other episode of show X and show Y. If you have 3 drives and 1 dies and everything is on it you lose everything. If you spread it over 3 drives you lose 1/3. These are all tradeoffs which need to be considered. There are also performance considerations.

mergerfs-tools already has logic in this space. You could look at all files in a directory, pick a preferred branch, and move files. Not too dissimilar to mergerfs.dup. The problem is how thorough you want to get. At what level do correlate? /a/? /a/b/? /a/b/c/? /a/b/c/d/? Focusing on specific directories with their files only (rather than where directories exist) would make it simpler but then the same issue arises. You lose every other season of X and Y rather than all of X. It the sense of orderliness this isn't so bad but in practice I'm not sure what it really offers.
