### ISSUE TITLE
mergerfs moveonenospc question and fsname issue

### ISSUE THREAD

**Issue by kevindd992002** [trapexit/mergerfs#614]
General description
===================
1.) What is the use case of the moveonenospc option? In general, why isn't it enabled by default? Based on how I understand its description, it looks like it is useful.

2.) I've just installed 2.26 now and when I `df -h`, here's what I see:

![image](https://user-images.githubusercontent.com/3907957/57585443-bd7a0200-751a-11e9-8862-d5f470ec0bdf.png)

I have `fsname=mergerfs` set in my `/etc/fstab`

Is this a bug?

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
`mergerfs version: 2.26.0
FUSE library version: 2.9.7-mergerfs_2.26.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.27
`
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
![image](https://user-images.githubusercontent.com/3907957/57585509-aab3fd00-751b-11e9-97a0-53b28fccea56.png)

* [ ] Linux version: `uname -a`
`Linux epsilon 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux
`
* [ ] List of drives, filesystems, & sizes: `df -h`
> Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           782M  8.7M  773M   2% /run
/dev/sda2        23G  1.3G   21G   6% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
1:2              10T  2.5T  7.0T  27% /mnt/storage
/dev/sda1       511M  132K  511M   1% /boot/efi
/dev/sda5       1.9G  5.7M  1.7G   1% /tmp
/dev/sda6       192G   61M  182G   1% /home
/dev/sda3       9.2G  248M  8.4G   3% /var
/dev/sdc1       2.7T  637G  2.0T  25% /mnt/disk2
/dev/sdd1       7.3T  2.6T  4.4T  38% /mnt/parity1
/dev/sdb1       7.3T  1.9T  5.0T  28% /mnt/disk1
tmpfs           782M     0  782M   0% /run/user/1000

**Comment by trapexit** [comment]
Please use the issue tracker for bugs and feature requests. There are other places for general questions.

1) You wish to try to move a file should writing to one drive return an out of space error. The reason it's not default is because it's 1) it's possibly expensive to do 2) won't likely work depending on the create function. If you use `mfs` as the create policy the likelihood it would succeed is very low. If you're using `ff` or something then perhaps it would. 3) `minfreespace` limits the likelihood that it would happen and is useful for other purposes.

2) There is already a bug report about this. #613

**Comment by kevindd992002** [comment]
Thanks. And when is that place for general questions? I thought you can ask anything here, sorry.

**Comment by trapexit** [comment]
You can as questions here but there are better platforms. I mention some in the [docs](https://github.com/trapexit/mergerfs#contact--issue-submission). email, twitter, discord, reddit, patreon.

**Comment by kevindd992002** [comment]
Thanks!
