### ISSUE TITLE
Which filesystem?

### ISSUE THREAD

**Issue by Chris230291** [trapexit/mergerfs#644]
Hello. I plan to replace my zfs media server with a 0 parity mergerfs setup.
Can anyone recommend a filesystem to use? I think xfs is supposed to be the best?
I was reading up on the "policies" and "mfs" sounds like it might be what I want. Am I right in saying that would put data onto the disk with the most free space by percentage? So if I mix drives, it would favour a 2TB drive with 1TB of free space over a 10TB drive with 2TB of free space?
I have seen the mergerfs tools, which look great. I see there is a "balance" utility in it which sounds like it does exactly what I am trying to achieve. But can mergerfs do this on its own? 

Thanks,
Chris

**Comment by trapexit** [comment]
> best filesystem
There is no "best". Whatever you prefer. I use xfs. Many use ext4, btrfs, and even zfs.

> mfs
Not by percentage. By raw storage available.

> mergerfs-tools
No, mergerfs can't balance after the fact. That's why I created the tools. To keep complex behaviors outside the core project. Better to update external tools than need to update the critical software path.

**Comment by Chris230291** [comment]
Thanks for the reply.
So there is no policy to fill by most % free space?
I suppose I can run a cron once a month to balance using your tools.

Thanks again,
Chris

**Comment by trapexit** [comment]
Why do you want to balance by percentage? A new drive that's 128MB has 100% free and would be used over a 8TB drive with 7.8TB used?

**Comment by Chris230291** [comment]
Ye it sounds a bit silly.
I have 2 new 10TB drives. I want to add my old 2TB drives. In my mind spreading the data by % free space would increase the chance files were being written/read from different drives and increase pool performance.

**Comment by Wintersdark** [comment]
I can speak for why.  

When balancing by percentage you keep spreading writes over all the drives.  At least from a media server perspective, this is beneficial because newer media tends to be accessed more, so that then spreads reads over all the drives too helping to avoid IO constraints and maintaining performance.   minfreespace allows to avoid issues with filled disks or should you add very small drives you don't want to use under normal circumstances.

I know I'd prefer to have mergerfs balance by percentage too.

'lus' allows even writes until you fill smaller drives, but it too results in filling small drives which, if you only have 1 very large drive (say you add a 10tb drive to a pool of 2-4tb drives) quickly results in only one drive being used.  

'mfs' prioritizes the largest drives, but those are also often the slowest drives and results in meeting IO limitations on those drives.

**Comment by trapexit** [comment]
Unless you have very specific usage patterns you won't on average increase performance. If you want to spread stuff around use `rand`.  With % based you'd still fill a particular till all had similar % so performance would suffer if those files were accessed at the same time. Once filled you'd bounce around the remaining drives similar to lus or rand. I doubt very much it'd make any real difference unless you knew the precise write and read patterns.

mergerfs-balance works by percentage because it was easiest to implement at the time. As with mergerfs proper ideally it'd have multiple policies.

**Comment by Wintersdark** [comment]
Yeah, I ended up going to lus for my case.  However, because my specific use case is leaning heavily on mergerfs.dup to duplicate files and provide seamless drive failure redundancy, filling up drives is counter productive - I need to ensure I don't end up with only one drive with free space, as at that point I'll be unable to duplicate anymore.  rand is ultimately going to fill drives evenly, so like lus it'll tend to fill small drives first.  In my current configuration I've only got a pair of 8tb drives, and everything else is some 40 drives ranging from 450gb to 4tb.  This means though that with 7tb free, only two drives are written to.  My media gets a single duplicate so it is written to both those drives, but my more important files get three - the third of which can no longer be created.

My workaround is to schedule running mergerfs.balance to rearrange by percentage and keep more drives available for writes, but I'd rather not have to do that as its a lot of extra chewing on the drives. 

With that said, i understand my use case is somewhat out of the box, just explaining where its useful to go by percentage.

**Comment by Chris230291** [comment]
OK. Since its an automated media server i'm not sure I would actually see any performance improvements anyways. It was more piece of mind.

So would this be correct to mount my disks and use the drive with the most free space?

```
/dev/disk/by-uuid/525deb43-3f8d-4a3b-9296-e13adc3af05f /mnt/mergerfs/disk1 auto nosuid,nodev,nofail 0 0
/dev/disk/by-uuid/eb9bba01-5f90-4365-9dbb-93c094a7288c /mnt/mergerfs/disk2 auto nosuid,nodev,nofail 0 0
/mnt/mergerfs/disk*     /mnt/Storage    fuse.mergerfs defaults,allow_other,minfreespace=50G,fsname=mergerfs,category.create=mfs 0 0
```

**Comment by trapexit** [comment]
> I need to ensure I don't end up with only one drive with free space,

Unless you have only 1 drive that's larger than all others that won't happen. And if you're really that close to full across 40 drives you've already been sleeping on the job wrt capacity management.

What kind of usecase is this where you're concerned enough about file availability that you're not using RAID? Assuming you have or can partition drives such that you could do RAID1 wouldn't that be better?

@Chris230291 No need for "defaults" if you're using a current version. Check out the recent docs. Otherwise... sure. That's fine.

**Comment by trapexit** [comment]
BTW... I'm not necessarily opposed to adding a percentage based policy but it does have a very niche usage IMO and without proper setup with minfreespace could result in unexpected placements.

**Comment by Chris230291** [comment]
Ok thanks for your time. Seems to be working nicely.

**Comment by Chris230291** [comment]
I think maybe this should be a new topic...
I am copying over all the data from my zfs RAIDZ2 to my mergerfs pool. Like I said before it seems to be working well. However I noticed that the drives keep displaying "zzz" in ubuntu disks utility. Seems they are aggressively spinning down. Is this normal?

Chris

**Comment by trapexit** [comment]
the spinning down has nothing to do with mergerfs

**Comment by Chris230291** [comment]
OK thanks. Any ideas?

**Comment by trapexit** [comment]
https://askubuntu.com/questions/39760/how-can-i-control-hdd-spin-down-time

**Comment by Wintersdark** [comment]
I understand my use case is more niche, and is why after asking initially I just used what was available.  

Capacity management:
For sure.  I'm Canadian, and finances aren't great.  I don't have access to the US super cheap HDD's, so I have to make do with what I have (which is why im running so many low capacity drives) as HDD's are very much more expensive here.  

RAID: with random capacity drives its not a good option.  Difficult and inefficient to make RAID/zfs pools that way, and difficult upkeep on failures (oh, a 450gb drive in a RAID pool failed, what do i replace it with?) and of course new drives are added very much piecemeal has funds allow.  I'm around 48 drives right now, so... Yeah.
