### ISSUE TITLE
Too large file for a single drive

### ISSUE THREAD

**Issue by OswaldKolle1977** [trapexit/mergerfs#652]
Hello,
I have a little problem...

General description
===================
Let's say, I have 3 drives 500GB each in a mergerfs (~1.5TB free space)
What happens, when I want to copy one file of 1TB size?

Expected behavior
=================
FIle is splitted into pieces, so it will fit on the sum of drives.

Actual behavior
===============
rsync runs endless... It seems like the system is trying to copy the (too) large file to the disks and repeats when failed

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ ] Linux version: `uname -a`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
mergerfs doesn't split files across branches. It is just a union of them. I thought that'd be obvious from the description and how similar systems work but I will make it more explicit in the docs.

rsync should error and indicate it's out of space. What are your settings?

**Comment by OswaldKolle1977** [comment]
I have to check the server in the evening... It is only a backup server (starts to rsync and sleeps till next evening)
I was surprised that the server was running so long - and then checked the disk sizes (and the union size) -- so I also have to check the log-file...

I would say that I have to change the default settings to fill the drives after another instead of balance the files on all disks... Just have to find out how... :-)

**Comment by trapexit** [comment]
The default policy isn't to balance. It picks the branch with the most free space with the relative path already existing. Changing the policy is just `category.create=<policy>`: https://github.com/trapexit/mergerfs#policy-descriptions

**Comment by OswaldKolle1977** [comment]
Thanks a lot!!

**Comment by OswaldKolle1977** [comment]
Sorry - I have to reopen it...
There are no errors in the log - it just "runs forever".....
This is my rsync call:
`env sshpass -p "XXX" rsync --verbose --log-file="/var/log/rsync.log" --recursive --times --archive --delete --perms --xattrs 'root@192.168.110.112:/nfs/' '/srv/backups/cloud' & wait $! omv_log "\nThe synchronisation has completed successfully."`

This is within the fstab:
`defaults,allow_other,direct_io,use_ino,category.create=lfs,minfreespace=200G `

-> So it should try to fill the disk with the least free size until 200GB left, then start the next.... At least one disk has enough space (> 1TB) for the virtualbox-file (size ~600GB)

And here the log - the last lines... (no Informations there...)

`2019/07/30 22:05:50 [29521] receiving file list
2019/07/30 22:06:52 [29531] .d..t...... VirtualBoxVMs/OSM/`

So it seams that there are no checks for the filesystem-sizes?!

----

Info:
`> mergerfs -V
mergerfs version: 2.27.1
FUSE library version: 2.9.7-mergerfs_2.27.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.27
`

**Comment by trapexit** [comment]
> So it should try to fill the disk with the least free size until 200GB left, then start the next.... At least one disk has enough space (> 1TB) for the virtualbox-file (size ~600GB)

That's not how it works. The file size is not known at the time it's created. The policy works *at* the time of the action. In the case of a file copy the one of importance is the file creation. In which case it follows the policy to find a drive to create the file on and then all writes go to that file on that branch. There is no way to know ahead of time how large a file is.

Of course there are filesystem size checks. It wouldn't work at all otherwise.

You're using an old version. You should always confirm issues with new releases. You also should provide more information as the ticket template describes. Filesystems are non-trivial to debug without precise instructions and metrics so the situation can be recreated. I created 3 10GB sparse files, formatted them xfs, mounted them on loopback, merged them, then rsync'ed a bunch of large files. It "ran forever" in that rsync will just continue even after getting ENOSPC errors. Seems like a bug in rsync to me as I'd expect it to exit immediately. Using cp it works just fine. I cp a large file into the pool and once the drive selected runs out of space it exits with a proper "No space left on device" error.

**Comment by OswaldKolle1977** [comment]
Thanks for the info!
I changed the fstab entry from lfs to mfs - so it started to write the large file on the (empty) disk with enough free space on it.

I really thought that the system gets the filesizes and even uses a drive with the amount of free space... So it was my false understanding and not the mergerfs.... Sorry again!
I will close the issue again!
Thanks a lot for your time!!

**Comment by trapexit** [comment]
It still doesn't address the odd rsync behavior but makes it less of an issue.

And no. A file copy is independent actions of a create, loop of writes, and close. The best that could be done is that a file that has been created, on close, could be moved behind the scenes but that would be an expensive operation on large files and would be a little complicated because if something tried to manipulate the file while being transferred mergerfs would have to block that till it moved. I don't see it being worth it. This is why minfreespace and the policies are provided to limit such problems. rsync being weird isn't something I can account for.

**Comment by OswaldKolle1977** [comment]
I don't know how rsync works - but maybe it looks for the "free disk space" of the target folder (where mergerfs says it is enough) - so the ENOSPC message will be ignored (because of a separate/second check)

**Comment by trapexit** [comment]
The behavior is the same outside mergerfs.

**Comment by OswaldKolle1977** [comment]
Of course, but mergerfs returns the sum-size of all drives - not the size of the corresponding destination folder (of a specific drive) - right?

**Comment by trapexit** [comment]
> Of course, but mergerfs returns the sum-size of all drives

It's configurable but yes. It won't return the most continuous available space. Regardless I don't see evidence rsync is checking. It is happy to start copying a 64GB file to a 10GB drive outside mergerfs.
