### ISSUE TITLE
Inconsistent folder timestamps

### ISSUE THREAD

**Issue by brianchandotcom** [trapexit/mergerfs#718]
General description
===================

I am rsyncing files from a single USB drive to a MergerFS mount made up of many drives.

I get inconsistent folder timestamps (files are fine).

Expected behavior
=================

USB: Folder A (2017), Folder B (2019)

MergerFS: Folder A(2017), Folder B (2019)

Actual behavior
===============

USB: Folder A (2017), Folder B (2019)

MergerFS: Folder A(Today), Folder B (2019)

**Precise** steps to reproduce the behavior
===========================================

rsync and compare the folders.

I notice this happens when the contents of Folder A is split across many drives. The drives that make up Folder A on MergerFS contain different timestamps.

System information
==================
Please provide as much of the following information as possible:

```
mergerfs version: 2.28.3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29
```

My Linux: Linux 5.5.5-200.fc31.x86_64

My fstab

```
/dev/sda /mnt/sda ext4 defaults 0 0
/dev/sdb /mnt/sdb ext4 defaults 0 0
/dev/sdc /mnt/sdc ext4 defaults 0 0
/dev/sdd /mnt/sdd ext4 defaults 0 0
/dev/sde /mnt/sde ext4 defaults 0 0
/dev/sdf /mnt/sdf ext4 defaults 0 0
/dev/sdg /mnt/sdg ext4 defaults 0 0
/dev/sdh /mnt/sdh ext4 defaults 0 0
/dev/sdi /mnt/sdi ext4 defaults 0 0
/dev/sdj /mnt/sdj ext4 defaults 0 0
/dev/sdk /mnt/sdk ext4 defaults 0 0
/dev/sdl /mnt/sdl ext4 defaults 0 0

/mnt/sda:/mnt/sdb:/mnt/sdc:/mnt/sdd:/mnt/sde:/mnt/sdf:/mnt/sdg:/mnt/sdh:/mnt/sdi:/mnt/sdj:/mnt/sdk:/mnt/sdl /mnt/mergerfs1 fuse.mergerfs allow_other,category.create=lus,minfreespace=100G,use_ino 0 0
```

df

```
a:b:c:d:e:f:g:h:i:j:k:l                 32665229104 2629506360 28378557708   9% /mnt/mergerfs1
/dev/sdf                                 1969875856  219867228  1649874636  12% /mnt/sdf
/dev/sde                                 1969875856  151139824  1718602040   9% /mnt/sde
/dev/sdh                                 1969875856  234621568  1635120296  13% /mnt/sdh
/dev/sdg                                 1969875856  151189568  1718552296   9% /mnt/sdg
/dev/sdi                                 1921803544  153666992  1670444440   9% /mnt/sdi
/dev/sdk                                 1921803544  153582468  1670528964   9% /mnt/sdk
/dev/sdj                                 1921803544  153579360  1670532072   9% /mnt/sdj
/dev/sdl                                 1921803544  153580544  1670530888   9% /mnt/sdl
/dev/sdb                                 1967953192  151266808  1716650068   9% /mnt/sdb
/dev/sdc                                 3844641608  118048560  3531225736   4% /mnt/sdc
/dev/sda                                 3844641608  100308684  3548965612   3% /mnt/sda
/dev/sdd                                 7441275096  888654756  6177530660  13% /mnt/sdd
```

**Comment by trapexit** [comment]
That's because of the getattr policy you use. Is the expectation that mergerfs would fabricate the data for directories? It doesn't (except for inode). It returns whatever data for whatever the directory chosen by whatever policy you have selected.

You are using `ff`... so it's that one.

**Comment by brianchandotcom** [comment]
Is there a way to force mergerfs to go through all disks and always ensure that folder attributes are the same?

So when mergerfs mkdir on disk 1, check on that dir's attributes and do the same for disk 2, 3, 4 and make them identical.

Or if I set an attribute on mergerfs, then set that attribute across all dirs on all disks backed by mergers.

I wouldn't even mind if the dir tree structure was replicated across all disks (very little space) and always enforced to be consistent.

Any way to add this as a feature? This is the one missing feature that would make this way better than LVM for me.

**Comment by trapexit** [comment]
How would that be accomplished? You can already apply policies to different functions and their default is already `epall` meaning it already gets applied to to all found entries explicitly. The problem is how do you know when something changes implicitly like directory times? Do you want literally every single function to scan through the directory of every file when modified and update the relevant {a,m,c}time? That'd be very expensive and impractical.

Can you describe the problem rather than the solution?

**Comment by trapexit** [comment]
Things that can't change:
* dev
* ino
* nlink
* ctim
* rdev
* size
* blksize
* blocks

Things that shouldn't be changed:
* uid
* gid

Things that can change (if permissioned):
* atim
* mtim

Would you want those set across all branches to whatever the directory of the created, deleted, renamed subdir or file? Even if it had a newer value?

Can you provide me with a very explicit example? I don't know what rsync options you're using and it has a lot of different behaviors. mergerfs is doing as it is told. If the directories are out of sync then it's related to that. Maybe it opens the directory and then calls a file descriptor based action rather than a name based one. In which case that might be easier to work around. But ultimately if something works on a file descriptor that works on a single object. It's not always possible or smart to distribute that behavior across all branches.

**Comment by brianchandotcom** [comment]
I think it may just be a limitation on union file systems. My root issue is that I just want consistent folder modified dates.

I get that with my single drive, but as soon as I rsync that to mergerfs, the folder modified dates are not consistent because they take the latest date of a folder (and there are many versions of that folder).

Anyways, great job on MergerFS. It's a great open source tool.

**Comment by trapexit** [comment]
mergerfs isn't taking the latest date of the folder. It uses whatever the policy you've configured returns.

You still just described the outcome rather than the problem. A problem with mtime is: "Plex uses mtime to indicate a directory should be scanned. I'd like the most recent mtime be presented." It's not a fool proof design because mtimes can be manually changed and only refer to the directory itself and not children but... ok... set `func.getattr=newest`. 

What is the particular problem you're trying to solve. Don't like the look? Functional problems with other software? 

And what exactly is your rsync command? As I said and as described in the [docs](https://github.com/trapexit/mergerfs#function--category-classifications) utimens is already able and will by default set the a or m time across all found. Only futimens will not due to it's nature. I could add something to force those file descriptor functions to change all found but I'm only guessing the problem. I can't know unless you tell me exactly the situation.
