### ISSUE TITLE
bugged NFS folders on latest stable rls

### ISSUE THREAD

**Issue by Termin8or666** [trapexit/mergerfs#772]
General description
===================
master build from december 2019 and january 2020 is working correctly for these exports so its not a permission issue
First I thought it was a kernel bug but only solution was to downgrade to earlier mergerfs build.
could this be a inode bug?

Same behaviour on 2 boxes tested with latest stable rls, 
The exported NFS folder is OK locally on the boxes.. all files / folders there and if a client makes a new folder to it, it copies ok but not visible from the nfs client. 

Expected behavior
=================
exports showing all files / folders (say its 3000 folders exported)

Actual behavior
===============
When exporting merged pool NFS client can only see a portion of the folders (50ish of the 3000 exported)

**Precise** steps to reproduce the behavior
===========================================

basic NFS export and mount on NFS client should reproduce this.

will make a vm for testing with more info if this is not a known issue already.

**Comment by trapexit** [comment]
You've not provided any config or setup. Could you please do so.

**Comment by Termin8or666** [comment]
example mount on nfs client:

10.10.10.9:/NFS/somestuff    /mnt/mystuff      nfs      async,rw,soft,intr,noatime,x-gvfs-show,nofail

NFS server export example:

/NFS/somestuff      10.10.10.11(rw,async,no_root_squash,no_subtree_check,nohide,fsid=3)

mergerfs info:
this is the downgraded working master from january 2020:

/mnt/disk* /NFS/somestuff fuse.mergerfs defaults,allow_other,hard_remove,direct_io,use_ino,category.create=epmfs,fsname=mergerfssomestuff,moveonenospc=false,minfreespace=20G,func.getattr=newest 0 0

mergerfs version: unknown
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.29

nfs server is on ubuntu 18.04 and client on 16.04

hope this give you some ideas whats going on with the stable release, 
after upgrading I first thought all was ok but it was after a long overdue reboot I noticed the problem. Probably when it remounted the pool on the new version.

**Comment by trapexit** [comment]
I have 2.29.0 on a Ubuntu 18.04 served with NFS to an Ubuntu 20.04 system with the exact same settings as you and it is working fine. All files show up and creating new files and directories work as expected.

**Comment by trapexit** [comment]
Why is mergerfs version "unknown"? That's not a stable build.

**Comment by Termin8or666** [comment]
this is the downgraded working master from january 2020,  as I said I had to downgrade to get it working.. 24/7 setup so not the best troubleshooting scenario. it displayed 2.29.0 version when that was installed.
could be just my setup as this has not come up before.. just find it curious that it happened on two different boxes. and used the same settings fine on all earlier versions.. 

will test some more later against other clients to see if it acts any different.

Thanks for all the good work and active development :)

**Comment by trapexit** [comment]
I'm not saying there isn't an issue just that I can't reproduce it with my setup and I'm unaware of anyone else running into the problem. The only NFS related issues are due to out of band inode changes which is a general NFS issue that I can only do so much to work around and have such a work around in the inode-calc branch.

**Comment by undaunt** [comment]
I actually was just experiencing a similar thing, only over the NFS share, and only in a folder with thousands of files where it showed a subset (58 of them).

I'm currently building mergerfs within a docker (https://github.com/IronicBadger/docker-mergerfs) forked to be built off ubuntu instead of debian jessie. Unclear if that is a problem or not? Not sure if I'd be able to reproduce the error again since I had already given up and decided to combine my NAS VM and my Plex VM as the faster solution.

shared mount: `/mnt/storage  *(rw,fsid=1,sync,no_subtree_check,no_root_squash)`
mounted: `nas-ip:/mnt/storage /mnt/storage  nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800  0 0` (also tried with noac)

My scenario was 18.04 serving 18.04.

Interestingly, all the files not only showed up properly on the host, but also on Windows over Samba - so definitely NFS related, unclear if its mergerfs related IMO.

**Comment by abstrakct** [comment]
I'm having the same issue on Debian 10 on a server with 4 hard drives joined together with mergerfs (underlying filesystem is XFS on all drives). I then mount the joined filesystem over NFS on my other computers. I used to have mergerfs 2.29 installed on the server (this package: https://packages.debian.org/bullseye/mergerfs) and everything was working fine, except for NFS stale file handle / fileid errors happening too often. When I saw the new inodecalc option I wanted to try it to see if it would solve my NFS problems.

So I cloned the repo (today, July 6, commit ddb435a4), did `make deb` and installed the package with dpkg. After a reboot mergerfs mounted fine with the inodecalc option, but when I mount the mergerfs over NFS I experience the same issues as described in this thread. For example, one folder with 289 files/directories only show 35 of them over NFS. I see the same problem in all folders with a lot of files/folders. It's curious that the number of files/folders that show up are between 26 and 37 in all folders I've checked.

I also tried to make a new directory with 100 empty files (named file-001 - file-100)  - only 41 showed up on NFS mounted side. If I delete file-001 on server, NFS shows file-002 to file-042. If I then edit file-042, file-042 disappears on NFS side, and file-043 shows up instead! Maybe the problem is related to mtime/ctime? It kind of looks like a subset of the oldest files/folders in a directory are shown.

Mount options on server: 
`/mnt/disk* /mnt/pool fuse.mergerfs defaults,allow_other,minfreespace=20G,fsname=pool,use_ino,inodecalc=path-hash,noforget,category.create=mfs,func.getattr=newest,cache.readdir=true`

Export:
`/mnt/pool   10.0.0.1/24(rw,fsid=1,sync,no_subtree_check,nohide,no_root_squash)`

NFS mount options on client:
`10.0.0.10:/pool  /mountpoint nfs4 rsize=8192,wsize=8192,auto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,noatime,nodiratime`

Let me know if I can provide any more information to help fix this. :)

**Comment by trapexit** [comment]
Yes. I've reproduced it and spent a good portion of the past week trying to track it down. Had a number of red herrings that have prolonged the investigation. The data being generated is identical. It's something to do with how NFS is interacting with the lifecycle of the dents buffer. It's nothing to do with any settings or data.

**Comment by trapexit** [comment]
Figured it out.

NFS does something I've not seen anywhere else. It will open the directory to read multiple times and ask for an offset it got from a different opendir instance. This seems wrong but I need to confirm.

**Comment by trapexit** [comment]
According to the FUSE kernel maintainer the behavior I'm seeing is expected but is contrary to the documentation. I can "fix" the issue in the same way it was prior to my changes but there is a risk of corrupted file listings (this was there before).

I can make that change for now and look into a better way to address it later.
