### ISSUE TITLE
rmdir action does not return ENOTEMPTY if first path does not have contents but other paths do despite policy=all/epall

### ISSUE THREAD

**Issue by t3nk3y** [trapexit/mergerfs#811]
**Describe the bug**
If the rmdir action is issues on a path that exists in multiple paths in the pool, if the first path is empty, but other paths have contents, the first path will be removed, while other paths are not.  As this action is ALL, all paths in the pool should be checked, and if ANY are empty, then the rmdir action should receive an error of ENOTEMPTY, rather than info based on the state of a single path in the pool.

**To Reproduce**
Create a pool that contains two paths.  The pool should have a category.create=ff
Mount the pool.
Create a directory in the pool.
Create a file in the directory.
From the first path in the pool, move the FILE(just the file, not the directory) to the same location in the second path
From the mounted pool, rmdir the DIRECTORY from a shell.

This will result in ONLY the first path having the directory removed.  However, from the perspective of the pool, nothing happens.

**Expected behavior**
rmdir command should return ENOTEMPTY, as from the perspective of the pool, the path is not empty.  However, instead, it accepts the command on the first path in the list, and returns 0, despite the fact that the action should be applying to all matching paths in the pool, and some paths are non-empty.

**System information:**
 - OS, kernel version:
Linux ps01 5.4.44-2-pve #1 SMP PVE 5.4.44-2 (Wed, 01 Jul 2020 16:37:57 +0200) x86_64 GNU/Linux
 - mergerfs version: 
FUSE library version: 2.9.7-mergerfs_2.30.0
fusermount version: 2.9.7-mergerfs_2.30.0
using FUSE kernel interface version 7.31
 - mergerfs settings
noauto,defaults,allow_other,use_ino,hard_remove,moveonenospc=true,minfreespace=100G,dropcacheonclose=true,ignorepponrename=false,func.getattr=newest,category.create=ff,nonempty
 - List of drives, filesystems, & sizes: irrelevent
 - A strace of the application having a problem: irrelevent
 - strace of mergerfs while app tried to do it's thing: irrelevent?

**Additional context**
This issue comes up when using a tiered cache setup with the scripts used as examples from the README.md, as rsync will move files, but not remove paths(folders).

I noticed this issue when attempting to delete a path from the pool from Webmin, which apparently, like bash, doesn't perform it's own check to make sure the path is empty, but instead it simply issues an rmdir, and listens for the filesystem response.

If you prefer, I can examine the code, and likely send a PR with a fix/improvement.

**Comment by trapexit** [comment]
Handling errors is tough generally because of the wide range of meanings but in this case it certainly makes sense to return that particular error. I'll take a look.

**Comment by trapexit** [comment]
BTW... doing things out of band will lead to race conditions as there isn't a way to manage them in any reasonable way. This particular situation might be addressable but not all such situations are.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/tree/rmdir-errors

Can you try that branch?

**Comment by t3nk3y** [comment]
Thanks for working on this so quickly, sorry I didn't get a chance to review your work till now.

While this DID fix the problem overall, I'm not sure if it's the best solution.  I tested it out, and reviewed the code changes, and while on the face of things, it looks like things worked correctly, under the hood this might not be quite right.

FSTAB:
```
/path1:/path2  /pool  fuse.mergerfs  noauto,defaults,allow_other,use_ino,hard_remove,moveonenospc=true,minfreespace=1G,dropcacheonclose=true,ignorepponrename=false,func.getattr=newest,category.create=ff,nonempty  0 0
```

BASH:
```
mkdir /pool/testdir
touch /path2/testdir/testfile
rmdir /pool/testdir
```
Correct error occurs:
`rmdir: failed to remove 'testdir': Operation not permitted`
However, if we look in /path1/ we will find the directory was ACTUALLY removed, despite the error and pool view giving the impression that no action was taken.

From the perspective of the user looking at the pool everything seems correct, so maybe this is fine?

However, I can see it leading to unexpected behaviors, and with more source paths, there are more scenarios.

As an example, if we have 3 paths, the results vary depending on which ones have the directory with the file in it.

**Example 1:**
```
p1: no file
p2: no file
p3: has file
```

rmdir results in:
```
p1: no dir
p2: no dir
p3: dir and file still exist
```

**Example 2:**
```
p1: no file
p2: has file
p3: no file
```

rmdir results in:
```
p1: no dir
p2: dir and file still exist
p3: dir and file still exist
```

**Example 3:**
```
p1: has file
p2: no file
p3: no file
```

rmdir results in:
```
p1: dir and file still exist
p2: dir and file still exist
p3: dir and file still exist
```

Example 3 might actually be the most expected behavior.

**Comment by t3nk3y** [comment]
I think the solution might be to check each path to see if they contain any files or directories(including hidden).  If they do, the entire function should return an error (ENOTEMPTY ?)

Because the actual behavior can't be determined until all paths are inspected, extra steps need taken before calling the underlying FS commands.

Furthermore, though I'm not entirely clear on the policies, I assume we can have a situation where the policy is NOT set to ALL for the action.  In which case it should behave differently, and act on only the first path that matches the filter(LFS MFS FF, etc..)?

---------------
As an alternate solution, though I still think that this might not be the most preferred behavior, though i think it should be easier to implement and should be just about as predictable, the loop in your existing code should not break when the first non-ENOENT error occurs, instead, it should continue through all paths, and keep the error code as the first(or most recent) non-ENOENT code.

This means that all three of my previous examples would produce the same results, with all paths that the rmdir function would succeed for having the path removed, and the paths that it would fail for would not have the directory removed.  From an overhead perspective, this feels like it makes a lot of sense.  Simply emulating the behavior of executing the command on ALL drives.

Again, this specific all path behavior should only occur if the policy is ALL

Thanks for your work, time, and consideration!

**Comment by trapexit** [comment]
What are you really trying to solve here? What's the problem? I'm aware of all the different ways things can be done but there are tradeoffs and it's not really useful to talk about different solutions without talking about the problem attempting to be solved so the different behaviors can be properly compared.

>I think the solution might be to check each path to see if they contain any files or directories(including hidden). If they do, the entire function should return an error (ENOTEMPTY ?

That doesn't actually replicate rmdir's behavior as rmdir is atomic. Checking the paths increases the cost of the behavior without actually making it atomic. Hidden directories are just like anything else.... I don't really understand your comment. A rmdir fails if it contains *anything*.

>not break when the first non-ENOENT error occurs instead, it should continue through all paths, and keep the error code as the first(or most recent) non-ENOENT code.

That's the same as the existing behavior you just get an error rather than success. And you lose errors all the same. The existing behavior was purposefully done in that if an error occurred then the first call would remove what could be removed and then the app would fail on a second call related with a real error. Which is perfectly valid since rmdir is atomic. With multiple actors it's perfectly valid to have a directory rmdir'ed and then immediately appear back. The app asked for rmdir. There was a success. So success was returned.

This patch was to provide the user with the relevant error, not to hide them, as you seemed to be concerned with.

>Again, this specific all path behavior should only occur if the policy is ALL

The algorithm should work fine regardless. Both the current and the patch do. Policies happen before behavior. I'm not going to create policy specific error handling.

**Comment by t3nk3y** [comment]
**Regarding Policies:**
In this case, at least, if the policy is ALL, and the desired behavior is to rmdir the directory on all paths in the pool, then it doesn't really make sense that the order of the paths in the pool would determine what paths the directory is removed from.  As it stands, it stops removing paths as soon as an error occurs.  This means if it fails on the first path, then the other paths do not get the directory removed.  If it fails on the last path, then all preceding paths get the directory removed, and if it fails in the middle, then the ones before that get removed, but the rest don't.  Whether or not the error is returned is not the point here.  The unpredictability of the actual behavior is the issue at hand.  Again, this is just my opinion, when I say "desired behavior" or "most desirable behavior" I mean, in your opinion, so it's not a problem if it's behaving as you want it to.

**What I'm trying to resolve**
Ehh, I'm sort of solving nothing here.  In my case, I noticed an issue while testing my setup(tiered cache as described on the readme.md).  However, the way in which I was testing is not actually the manor in which I am actually using the pool.  My end user setup is OwnCloud sitting on top of a MergerFS pool.  The OC drive is always accessed using the OwnCloud sync client, and when I tested OC, it does not have an issue with either version of this.  OC seems to check the content of the folder first, remove contents, then remove directory.  As such, there isn't an issue.

However, Webmin behaves differently, and there is likely other software that takes the same approach.  It tries to issue rmdir on the directory, and IF there is an error, it then drills in to the path and deletes contents, then issues rmdir again when it finishes(or perhaps it's essentially just doing "rm -r").  The experience from Webmin depends on the order of the paths in the pool, and whether or not we are using the patch.  Without the path, Webmin behaves as if the directory was deleted, and shows no error, but the directory remains in the UI.  Trying again, this will repeat until it reaches the directory with content, then the directory gets deleted.

With the patch, Webmin succeeded, and I think it would continue to do so in all scenarios.  Mergerfs deletes directories from pool paths until it hits the one with content, returns error to Webmin, webmin switches to deleting contents, and this completes for the path with content, and any following paths with content.  But, again, this is specific to Webmin, and other applications that don't behave the same as Webmin are likely to run in to problems.

If just using the bash rmdir command, the user would see different results with and without the patch, and different depending on the order of the paths in the pool.  Without or without the patch, the actual behavior will be unknown, it might have deleted the directory from some paths, or it might not, it all depends on the order of the paths in the pool(and which paths contain the contents).  As far as rmdir is concerned, the only difference with or without the patch is whether or not an error is returned when an rmdir fails, somewhere.

**What I think makes the most sense**
I don't think it makes sense for an action like this to have seemingly "unpredictable" behavior, at least not when using the ALL policy.

If using FF, EPFF, LFS, MFS, etc, it makes sense that ONLY the selected path should be considered, and the error, or lack of error should only be returned for the selected path.

For ALL policy, things change.  The documentation suggests that the action will be carried out on ALL paths.  But that isn't what happens right now.  Right now, it is carried out on some paths, and not on others, and it depends on the order of paths in the pool, and the contents of the paths.

IMO, if any 1 path in the pool has the error, an error should be returned, AND, the actual behavior should be either:
- No directories are removed.  The user sees an error, and can expect that the entire request was rejected.  I think this best replicates what a user would expect to happen when receiving an error while trying to carry out the action.
- All directories that didn't return an error, are removed.  The user sees an error, but knows that any paths that the action was valid for, had the error carried out, but whichever paths had an error, did not.
Furthermore, with both behaviors, the pool view will function identically, and the interaction with it from all three applications I mentioned, and likely all other applications, would be identical to what it would be if working on a real path instead of a pool view.

**Final notes**
My personal issue is resolved with or without the patch, and even my test scenario is a non-issue WITH the patch.  But I think the REAL behavior could be improved.  It is of course entirely up to you to decide, and I'm sure with your more experienced considerations, you will make the best choice for your product.  That said, if you are interested in what I'm trying to suggest, and my text based explanation is still failing to get my point across, I'd be happy to create a video demonstrating the behaviors I'm referring to.

Again, I greatly appreciate your efforts and time here.

**Comment by trapexit** [comment]
>  The unpredictability of the actual behavior is the issue at hand.

There is *always* unpredictability with a situation where things are being changed out of band or there isn't a proper means to respond to a situation.

>. As far as rmdir is concerned, the only difference with or without the patch is whether or not an error is returned when an rmdir fails, somewhere.

No. That's not the only difference. There are several ways to manage the situation. You only have 1 return value but you have possibly several things to work on in a non-atomic way.

The existing behavior ignores errors IIF there is a success. The patch returns immediately if there is an error because that's what it seemed like you wanted. There are a number of other ways it could work. Majority error. Ignore certain errors. Etc. All of those have their own issues depending on what the software is doing.

> I don't think it makes sense for an action like this to have seemingly "unpredictable" behavior, at least not when using the ALL policy.

You keep talking about different policies but there is no difference ins behavior for policies.  The algo is the same. Current behavior is exactly the same whether or not there is 1 or N directories to remove. If there is a success then success is returned. If all error then an error is returned.

>For ALL policy, things change. The documentation suggests that the action will be carried out on ALL paths. But that isn't what happens right now. 

Yes, it is. [The existing behavior is to iterate over all paths and call rmdir.](https://github.com/trapexit/mergerfs/blob/master/src/fuse_rmdir.cpp#L54) The documentation explicitly says this and that's what the code does. [The docs also say](https://github.com/trapexit/mergerfs#tips--notes)

*Since POSIX functions give only a singular error or success its difficult to determine the proper behavior when applying the function to multiple targets. mergerfs will return an error only if all attempts of an action fail. Any success will lead to a success returned. This means however that some odd situations may arise.*

The last sentence would be true if an error was returned as well but there were some successes. It all depends on what the client software does. Why it was calling rmdir. What it does after that. Etc. This isn't unique to rmdir. It applies to most of the functions. What do you do if a chmod fails? Do you stop? Try to reverse the chmod where it succeeded? Or open? If one fails do you try others? Or readdir? If a directory fails to read do you fail the whole call? Do you return only what you can read? There is no "correct" answer. There are just compromises.

>IMO, if any 1 path in the pool has the error, an error should be returned, AND, the actual behavior should be either:

> No directories are removed.

That's not possible. The only way to know if a directory can be removed is to call rmdir. This isn't a database with transactional behavior and it isn't easy or secure to try to fake it by checking privileges. And trying to remove dirs and then create them again if something fails would be a mess.

>All directories that didn't return an error, are removed.

That's what it does today. It just returns success in that case because it's perfectly valid for a directory to be removed and then it immediately be back due to multiple actors. Any software which is, for instance, recursively removing paths would simply fail one directory up if there was a failure. Same is true with unlink.

>The user sees an error, but knows that any paths that the action was valid for, had the rmdir carried out, but whichever paths had an error, did not.

Which error? Any? Is that less confusing than a success returned and it still there? Or it returning EACCES when another failed due to EBUSY or ENOTDIR or EPERM or EROFS? I don't see any strategy working for all situations or not being somewhat confusing. The interface simply doesn't enable communicating what's going on. mhddfs would do as the patch does. Some people didn't like it. Similar filesystems are overlays so they don't behave the same way so there isn't much to compare.

**Comment by t3nk3y** [comment]
I'd like to start by saying, I understand everything you are saying, it all makes perfect sense, all of your points are, of course, on point.

**What happens in patch vs no-patch**
You are of course correct, you know your software far better than I do.  I had not tested the 1 2 3 scenarios I mentioned, just 2 of them, on the non-patched version.  And I made an incorrect assumption about the non-patched behavior when stating what would happen in the 3 scenarios.  I did test all 3 with the patched though.

So, **sorry** about that, I wasted some more of your time there, I should know better.  I did re-test non-patched now, and confirmed that it works as you stated.

**Policies**
Before going forward with talking about policies, I'm still not ENTIRELY certain here, but do "actions" support any other policy other than ALL?  If not, then, I see why you are saying the policy doesn't matter.  And it certainly makes sense that ALL(or EPALL) would be the only policy that applies to "actions"

**What I'm Proposing**
I think there is some confusion about what I'm proposing to do.  I am NOT proposing performing rmdir on all paths to test if the action works, then trying to undo those actions.  I'm right there with you on the concept that this would be a BAD idea.

I'm proposing giving special sauce treatment to rmdir(the filesystem action, not the bash command).  Before I even mention why, I would understand why you would have objections to doing this, both on the front of it being one off behavior for individual commands and on the fact that it might just be a matter of guessing at the behavior of an actual OS implementation of the command that is being executed.

That said, what I think makes sense(and again, this is one of two options) is to, essentially(maybe not exact implementation), execute a search on the pool view using EPALL, and if that returns any content, then have mergerfs return an error stating that the path is not empty, and in this case mergerfs does NOT execute rmdir on ANY of the paths.

This prevents the need to undo any actions taken.  It also makes this error take precedence over all others, preventing the execution of rmdir until it is valid based on content, and then you resume the normal behavior of executing the actual command with the current code.(or some other flavor of followup behavior)

**The other proposition**
The other option being to execute rmdir on all paths, just as you have been doing, but to return an error after executing on all paths.  What error to return?  Yea, that's a problem.  I'd say, the first?  I dunno.

I kinda feel like this "execute on all despite an error or not" is actually a separate issue from this rmdir situation.  With rmdir, I'm looking at a specific command, but the concept of applying to all paths or not really falls back to the general issue of what to do about an error when working actions over multiple paths.

Therefore, how about we split this in to two separate issues.

1. Proposal to provide special pre-check on rmdir command - check all paths for content and return ENOTEMPTY(assuming that's the right error code) if any dirs have content before running rmdir command.
2. Proposal for different error handling of actions - Have actions always apply to all paths, return error or not, etc..  Maybe implement policy to allow user to specific behavior.

Implementation of the first proposal does not preclude an implementation of the second.  "Fixing" rmdir still leaves the question of what happens after handling the potential ENOEMPTY error.

If you think it makes sense to split the discussion, then I'll open another issue for 2. and we can keep the rmdir discussion here, and if you are up for tackling the larger feature change on actions and errors, we can discuss that there?

Thanks again for your time and efforts!

**Comment by trapexit** [comment]
> I'm still not ENTIRELY certain here, but do "actions" support any other policy other than ALL? 

Yes. You can use any policy on any function. They just behave slightly differently depending on category as described in the policy section.  The error handling algo is the same no matter the policy. If there is a success, a success is returned (0), if all error then the error is returned. That behavior is the same if there is 1 file acted on or 100.

> rmdir(the filesystem action, not the bash command).

The command is just a wrapper around the syscall. I've no way to control the former outside managing the latter.

> execute a search on the pool view using EPALL, and if that returns any content, then have mergerfs return an error stating that the path is not empty,

This is what I was referring to before. The only way to know, for a fact, whether or not a directory can be removed is to call rmdir. Otherwise you have a race condition. There is also the problem of non-standard filesystems on which that could be more complicated. You could possibly be able to rmdir a directory with content. If we ignore the non-standard filesystems: how do you know if a directory is empty? You have to opendir, readdir, look through the files, and closedir. That would be increasing the cost of a rmdir substantially. Casually that wouldn't have a notable impact but effectively doing an `ls` on every directory when trying to remove it will impact rmdir heavy workloads.

Another example of non-standard filesystem issues... while copying a file... some filesystems will disallow a chown or chmod by user X even if technically owned by user X. The work around was to specifically check if the values are valid after they are called and failed. If I didn't add that very specific work around then what is technically correct is in fact broken on non-posix filesystems (which are regularly used with mergerfs).

>Proposal for different error handling of actions - Have actions always apply to all paths, return error or not, etc.. Maybe implement policy to allow user to specific behavior.

That certainly can be done but would need to independently settable for every action, you can't just generalize these things as every function is different and expectations are different on different filesystems, and I question the usefulness given up till this ticket zero people have brought it up.

> Proposal to provide special pre-check on rmdir command - check all paths for content and return ENOTEMPTY(assuming that's the right error code) if any dirs have content before running rmdir command.

There is no way I'm making such a behavior default but if you need this behavior I can make it optional.

**Comment by t3nk3y** [comment]
How about making the patch behavior optional (Action Fail on First Error, AFFE)?
I do find that this new behavior solves a lot of potential problems, and provides a fair process for allowing the user to troubleshoot the errors one by one.

To be fair, the issue at hand ended up having no effect on my own personal scenario.  This is a more a of a theoretical improvement, so if you don't feel it's worth the effort or potential for bug/hassle to make it a permanent option, please don't do this just for my benefit.

I'm going to open a separate issue for the rmdir pre-check

**Comment by trapexit** [comment]
> How about making the patch behavior optional
>To be fair, the issue at hand ended up having no effect on my own personal scenario. This is more a of a theoretical improvement,

Not sure you're consider the scope of this proposal. This isn't trivial. You're talking about having to reconsider the behavior of almost every single thing in mergerfs. rmdir isn't unique in this situation. It's just the one you are looking at. What about chmod? chown? mkdir? utimens? link? removexattr? rename? setxattr? truncate? unlink? symlink? How to manage access and getattr and getxattr and ioctl and listxattr and open and readlink? And then all the other functions that work on file handles? Another 10+ functions?

Calculating what the return value is is relevant to all of these and they all behave more or less the same as today. To change how the return value is managed requires a new setting for all of them. 

And not to forget that some of these absolutely **will** break things that people don't expect to break today. Special handling would have to be applied to handle EROFS, ENOENT, etc which would increase the complexity and cost of every function. This is a massive change.

**Comment by t3nk3y** [comment]
I was really just thinking about the patch you already made, becoming optional, as opposed to implementing a larger effort.  So maybe more of an "rmdir Fail on First Error (RMDIRFFE)"?

But perhaps implementing this ONE action doesn't make sense, and the larger change set isn't worth the effort unless users are experiencing issues related to this.

I do feel that rmdir is a bit of a special case action though.  I don't think any other action can have errors related to the content of a directory, only rmdir needs this special behavior due to it's unique nature, and the interaction of that nature with the special filesystem(interface) that is mergerfs.

**Comment by trapexit** [comment]
Unique in what way? If a program tries to chown something and fails 1 of 5 ... it returns success today. Same as rmdir. And depending on what the software does that may or may not be a problem. Same as rmdir. This is true of a number of functions. What is proposed is different from some bespoke, rmdir only behavior that for instance will return ENOTEMPTY if any do. That's different from making it return an error any time it hits one without nuance. For instance... you call rmdir and get a ENOENT. Did it disappear? Should you error since you wanted it gone anyway? 

If I'm going to create error handling "policies" for functions I can't just do it for one. That's different from tailoring the error handling for a function with special needs.

**Comment by t3nk3y** [comment]
It's unique because it's the only command that will fail depending on the content of other paths(the directory contents), am I wrong?

**Comment by trapexit** [comment]
I suppose that is unique in that it's a directory specific error but it's not unique in that it's atomic, that the error has meaning relative to what the app is doing, or that it is an error unique to a particular call. The ultimate impact of the error depends on the context. rmdir and unlink can both error with EBUSY meaning it's used by something else as a mount point for instance.

**Comment by t3nk3y** [comment]
But only rmdir can error if the directory contains another directory that is a mount.  At the system level, the content of the directory has to be considered, before the application layer.  I believe that is where rmdir is unique.  As far as filesystem contexts go, it's the only call that requires inspection of other objects on the filesystem.  And when dealing with a unique case like mergerfs, where a directory can essentially have contents that span multiple other filesystems, that merger layer is the logical place to place this logic.

**Comment by trapexit** [comment]
My point is that rmdir is only unique in the fact that it is a directory. If you're going to special case it then you must special case everything that needs it. There are multiple calls that have error conditions depending on how the app interacts with the filesystem and since it's nearly impossible for mergerfs to recreate the behavior precisely you must make some compromises. And those compromises **will not** work in all cases. 

> it's the only call that requires inspection of other objects on the filesystem

No, it's not. There are a number of conditions and errors that rely on other aspects of the system. EBUSY as I pointed out. Errors when the path contains non-dirs. Dealing with EXDEV (rename and link).

I'm not arguing that ENOTEMPTY shouldn't / couldn't be more thoroughly handled. I'm arguing that this is not a unique situation. Many other functions, depending on how the software interacts with the system, can lead have problems in a union filesystem due to how errors are handled. If you are chmod'ing files and one fails and then you try to rename... it'll fail technically but how the software interacts with the system will determine if it notices or cares.

**Comment by trapexit** [comment]
As I said before... I will make this an optional feature but other functions should be audited for similar behaviors. Just making it fail on first error isn't going to fly. It needs to be per function focused.

**Comment by t3nk3y** [comment]
Okay, let me know if you would like me to test anything out for you.  Hope to be of, at least, a little help.

**Comment by trapexit** [comment]
#832
