### ISSUE TITLE
HELP accidental rm -r on a bind mount of pool subfolder

### ISSUE THREAD

**Issue by zilexa** [trapexit/mergerfs#896]
I was setting up nfs, earlier I had mounted a folder inside my pool (/mnt/pool/Photos) to /srv/nfs/Photos..
I was confident that mount no longer existed (not in fstab, not in /etc/exports), it was also an empty folder. 

I just did `rm -r srv/nfs/Photos` and now /mnt/pool/Photos is empty. 

Panic mode here as yesterday I moved a whole bunch of photos to that dir, and I was just about to run a backup of it all. 
The merged disks are 2 btrfs harddisks (not using raid ofcourse). 

Is there a way to restore the data as I suppose only an index is deleted? Sorry I am no fs expert and in panic.

**Comment by trapexit** [comment]
If you deleted the files you deleted the files. You can look up details on possible data recover of btrfs but your success will depend on if you've continued (write) to use the filesystem.

Can try something like photorec

https://www.tecmint.com/photorec-recover-deleted-lost-files-in-linux/

Otherwise this has nothing to do with mergerfs. Sorry about your situation but you'll have to look up general data recovery tooling and btrfs tooling.
