### ISSUE TITLE
Per directory location rules?

### ISSUE THREAD

**Issue by Crowley007** [trapexit/mergerfs#901]
I tried searching and reading docs but could not find a definite answer. Is it possible to have rules to force directories to a specific disk? 

For example, extracting compressed files work much better if reads and writes are on separate physical disks.

**Comment by trapexit** [comment]
The location of a file creation or the file opened is based on the relevant policy.

https://github.com/trapexit/mergerfs#policy-descriptions

This is no special logic that attempts to spread out behavior outside the policy. What are you suggesting? Watching the paths being accessed and try to keep them from working on the same branch? Any optimization for some single usecase tends to complicate or not work at all for others. If you want to limit where stuff exists it's best to just use a policy which takes paths into account and manage the paths as you see fit.

**Comment by Crowley007** [comment]
I'm pretty new to this, trying to move from Windows 10 Home server setup to Linux and I'm trying to match my Drivepool setup with mergerfs. With Drivepool it just works, no idea how it's done.

Mostly I want files and folders balanced and spread out between disks and for 99% of the files it does not matter which disk they are on. But there are few exceptions like the one I gave above. Also If files are moved between directories, I want them to stay on the same physical disk.  I will probably be adding duplication for some folders, but have not gotten that far yet.

I couldn't figure out a policy to match all that.  I could move the needed directories outside of the pool, but when I move files inside the pool I guess there is no way to keep it on the same physical disk.

But if what I want can't be done, I  just need to figure out something else.  Anyway, thanks for the software.

**Comment by trapexit** [comment]
I can't tell you if it can be done because I'm really not sure what you're trying to do. When a file is created the location is decided based on the policy. The behavior of rename or link depends on your policy. You'll need to describe the *precise* situation for me to comment. Extracting compressed files isn't really a thing. It's the opening of one, existing file, the creation of new directories and files, and then the writing to them. From the filesystem's prospective entirely independent events.

**Comment by Crowley007** [comment]
Ok, so 3 directories on the pool.

/Compressed -> **Disk1**
/Extracted -> **Disk2**
/Final Destination -> On both


So I extract a file.  If I read from and write to the same mechanical disk, performance suffers.  So I want /Compressed and /Extracted to be on a different disk. When the file is fully extracted, it will be moved to "/Final Destination". Optimally this will be on Disk2 initially so it will move instantly, but can be balanced wherever when a scheduled balancing runs.

**Comment by trapexit** [comment]
1) mergerfs doesn't have scheduled balancing. The location of files are determined at the time they are created.
2) The creation location of files is exclusively controlled via policies. There is no way to change policies based on location within the pool. In *nix/Linux you can create all the filesystems and bind mounts you wish so generally speaking it's not been necessary to add such complexity to the project when there tend to be simple alternatives. There is no way to force /Extracted to be a target *because* /Compressed is being used. You can use policies which use existing paths to limit the selection of a branch but that's not the same thing. IE... you can have /Compressed on one branch and /Extracted on another and then use epmfs or mspmfs or related to filter out the branches without /Extracted. And depending on the policy and the ignorepponrename setting the rename can succeed on the "move" from /Extracted to /Final (it's not a move. It's a rename. there is no such thing as "move" in a filesystem.) 

I'm not aware of any good way to definitively do what you ask. Maybe you could keep track of every read-only open request from a process and the location that was opened and then exclude those from future create file requests. The fact the requests come from the same process is about all you have. That wouldn't account for other processes doing whatever they do. And if you did account for the same but across the whole system I think you'd very quickly find that it'd be a fruitless endeavor. Any reasonably busy system would have reads and writes going to numerous drives. 

IMO you're overthinking this. Yes, in well understood, bespoke situations that is ideal but it is not something that scales on a busy system and isn't something that can be clearly determined. 

If you feel otherwise you'll have to very expressly define the information and algo used to determine where a file gets created.

**Comment by Crowley007** [comment]
Doesn't mergerfs.balance do just that, balance files on demand?

Yeah, maybe I'm overthinking it, but that's how my current Windows setup works. I'm just trying to replicate it in Linux.

The policies you suggested might get me closer at least, I will have to try it.  Thanks for the support.

**Comment by trapexit** [comment]
That's a tool that shuffles around files out of band. It does not replicate mergerfs' policies. It's mostly intended for people who screwed up and chose epmfs and wanted mfs.

As for policy suggestions... mfs is what I tell most people.

**Comment by Crowley007** [comment]
This part still confuses me, can't I balance files between disks after the fact using that tool (or any other way).

**Comment by trapexit** [comment]
I don't understand what you're getting at or confused about. Of course you can move files around but that's nothing to do with mergerfs itself and what it does and how it works. mergerfs works by proxying filesystem functions. You call "create" it decides what branch to do so on. If you're moving stuff around after the fact that's a separate thing and ultimately unrelated to mergerfs.

**Comment by Crowley007** [comment]
I'm referring to my example above. If I can set the policies to do what I want, those extracted new files will be created and moved/renamed on Disc2 only. I want to automate the process of balancing Disc1 and 2 according to free space for example once in a 24h period. 

I'm asking I can use scripting/scheduling and mergerfs.balance to do that.

**Comment by trapexit** [comment]
You can of course move stuff around after the fact out of bounds. Yes, mergerfs.balance will move files around out of bounds. But the only way you're going to get reads from one drive and writes to another **guaranteed** is to use a policy which takes paths into account and if you ever create that path on another drive it will end up being a target for future "create" calls or whatever.

**Comment by Crowley007** [comment]
Yeah I get that, but if the path remains the same all the time, I assume it would work like I want. But the original question is solved, I will have to to play with the policies and try it out. Thanks.
