### ISSUE TITLE
ZFS: 10x+ slower performance

### ISSUE THREAD

**Issue by KyleSanderson** [trapexit/mergerfs#902]
**Describe the bug**

Mergerfs is 10x slower than accessing the ZFS disks directly. XFS does not seem to suffer from the same issue.

**To Reproduce**

```
zfs-0.8.3-1ubuntu12.8
zfs-kmod-0.8.4-1ubuntu11.2
```

`mergerfs -o allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs T41:T81:T83 merge`

```
zpool create \
    -o ashift=12 -o autotrim=on \
    -O encryption=aes-256-gcm \
    -O keylocation=prompt -O keyformat=passphrase \
    -O acltype=posixacl -O canmount=on -O compression=lz4 \
    -O dnodesize=auto -O normalization=formD -O relatime=on \
    -O xattr=sa \
    T81 /dev/sdc
```

**Expected behavior**

No major hit.

**System information:**

 - OS, kernel version: `Linux 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - mergerfs version: `mergerfs version: 2.32.4`
 - mergerfs settings
 - List of drives, filesystems, & sizes:
   - `df -h`
   - ```
 sdb      8:16   0   3.7T  0 disk
├─sdb1   8:17   0   3.7T  0 part
└─sdb9   8:25   0     8M  0 part
sdc      8:32   0   7.3T  0 disk
├─sdc1   8:33   0   7.3T  0 part
└─sdc9   8:41   0     8M  0 part
sdd      8:48   0   7.3T  0 disk
├─sdd1   8:49   0   7.3T  0 part
└─sdd9   8:57   0     8M  0 part
```

**Comment by KyleSanderson** [comment]
`cache.writeback=true` has no impact. Single file performance doesn't seem to be impacted, `ls | parallel rsync -avlHAXWES --progress --update {} /mnt/merge` shows the issue between the two.

**Comment by trapexit** [comment]
Can you define what you mean by "access"? Provide explicit, simple tests to reproduce? Have you compared straces of mergerfs against xfs vs zfs? mergerfs doesn't act any differently between the two.

**Comment by trapexit** [comment]
And have you gone through the performance section of the docs to compare settings?

**Comment by KyleSanderson** [comment]
> And have you gone through the performance section of the docs to compare settings?

I have, yeah, also old bugs where people had invalid ashifts and similar. strace is pretty normal, stating on each, ENOENT, then rsync writes the file. ZFS doesn't use the linux cache (I don't know why - it seems like a NIH issue) - I wonder if this more of a FUSE + ZFS thing (ZFS is the kmod as you can see) than a mergerfs thing.

**Comment by trapexit** [comment]
@ironicbadger Have you ever run into any issues with mergerfs & zfs?

**Comment by IronicBadger** [comment]
Not that I noticed. Ping me on discord tomorrow and we can check this out together if you like.

**Comment by KyleSanderson** [comment]
I've joined the Discord, feel free to ping when you're available and we can look together. I'm PT based.

**Comment by trapexit** [comment]
The write issue appeared to be due to running rsync with `-S, --sparse`. It drops the [write buffer](https://github.com/WayneD/rsync/blob/05540220a92dd06b62f240f6178921dde5697dd3/rsync.h#L155) size to 1KB vs the normal 32KB. Due to the increased latency mergerfs adds the lowering of write sizes kills performance more than it normally would since the client (rsync) is issuing writes sequentially. Enabling writeback caching may help and I've considered adding my own writeback caching behavior into mergerfs to augment such situations but the roundtrip into mergerfs vs being stopped at the kernel may mean it wouldn't help as much as just using kernel writeback caching.

The `ls` perf issues seems to just being general slowness due to size of files to query combined with the less than optimal way FUSE and POSIX manages all this. Improvements here are already on the roadmap.

**Comment by KyleSanderson** [comment]
Made a PR in the other repo, as it's moving whole, complete files it makes sense to not use sparse there. While I'd prefer to close this issue after the tools issue is improved, it's not a preclusion to do so.

Thank you very much for spending the time with me today to determine what was going wrong with my setup (which was indeed user error) and for offering excellent support for OSS.
