### ISSUE TITLE
Remounting underlying as Read-Only

### ISSUE THREAD

**Issue by bluecmd** [trapexit/mergerfs#903]
Hi,

I am trying to understand if mergerfs can handle dynamically changing a pool member to read-only.

The situation I have is that when mergerfs has successfully filled up a member I wish to remount it as read-only (`mount -o remount,ro ...`) to ensure the filesystem is flushed to disk and that no more modifications can happen to that filesystem by mistake.

I have tried this:

```
mkdir 1 2 merger
dd if=/dev/zero of=1.fs bs=1G count=1 status=progress
dd if=/dev/zero of=2.fs bs=1G count=1 status=progress
mkfs.ext4 1.fs
mkfs.ext4 2.fs
mount -o loop 1.fs 1
mount -o loop 2.fs 2
mergerfs 1=RW:2=RW $PWD/merger/ -o allow_other,use_ino,minfreespace=10M
mkdir merger/test # This ends up on 2/test for me
mount -o remount,ro 2
touch merger/test/3
touch: cannot touch 'merger/test/3': Read-only file system
```

Ideally mergerfs would catch that "read-only filesystem" error and recalculate a new place for the file, but it appears it does not do that. Maybe I misunderstood the policies but I could not find anything related to read-only filesystems there at least. Fwiw, creating a bunch of other directories in the root makes them all end up in the `1/` directory, so it appears it is just the `2/test/` directory that is forever read-only.

If I need to tell mergerfs this during runtime I can live with that, but I tried using `mergerfs.ctl` like this: `sudo ~/mergerfs-tools/src/mergerfs.ctl set srcmounts /home/bluecmd/merger/1:/home/bluecmd/merger/2=RO` without success. Not sure that is meant to work.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#filtering

It's described here. read-only drives are ignored for creates. 

mergerfs, unless you are using statfs caching, will always get the latest information from the filesystem. It's been a while but I recall that remount'ing to read-only (manually as you did or automatic like ext4 on error can) does not get picked up by statfs. If you strace mergerfs as shown in the docs it should be easy to see what data is being returned by the kernel. 

Basically mergerfs is being lied to. Assuming it's a create error then I could perhaps mark the branch as read-only to force it to be ignored and then try again. The problem is then I don't have a situation to do the reverse. Know when it's no longer read-only ... because i'm ignoring it all the time. I could out of band try to create files I guess but generally am not a fan of that if it can be avoided.

Are you trying to touch a file that already exists or not? Because if you are that is a whole different thing. Yes, that setting the branch RO should have the same effect as a read-only mount as per the docs.

**Comment by bluecmd** [comment]
> Are you trying to touch a file that already exists or not?

No, I'm creating a new filte in an existing directory.

> Yes, that setting the branch RO should have the same effect as a read-only mount as per the docs.

Can you confirm that it should work to do this runtime? When I tried with mergerfs.ctl it seemed like it ignored my `=RO`.

For my use case it is essential that making the underlying as RO is done online, there will potentially be many many IOPS against the mountpoint so unmounting and mounting mergerfs to refresh the cache is out of the question.

What I'm reading from your reply is that my usecase should work as long as I am not using statfs caching. I'll do some more experimenting and see what I can uncover.

**Comment by trapexit** [comment]
I just did a basic test of remounting a filesystem and it does look like the ST_RDONLY flag gets updated. Perhaps my memory was bad or it's changed over the years. Either way... you are using path preservation policy so your example isn't good. If you've created a directory on only a single branch then when creating a new file in that path only those branches with it are considered. In that sense it is doing exactly as you requested. A new file is denied because /test/ exists only on one branch and that branch is now read-only.

https://github.com/trapexit/mergerfs#filtering

>If all branches are filtered an error will be returned. Typically EROFS (read-only filesystem) or ENOSPC (no space left on device) depending on the most recent reason for filtering a branch. ENOENT will be returned if no elegible branch is found.

**Comment by bluecmd** [comment]
Ah, I see - thanks! So changing to e.g. `mspmfs` should work better?

**Comment by trapexit** [comment]
Anything that doesn't have strict path requirements, yes.

**Comment by bluecmd** [comment]
Works flawlessly, thanks!
