### ISSUE TITLE
Documentation, more details for deprecated mount options would be useful

### ISSUE THREAD

**Issue by tig987** [trapexit/mergerfs#907]
**Describe the bug**

The Readme describes some mount options as deprecated:

- direct_io: deprecated - Bypass page cache. Use cache.files=off instead. (default: false)
- kernel_cache: deprecated - Do not invalidate data cache on file open. Use cache.files=full instead. (default: false)
- auto_cache: deprecated - Invalidate data cache if file mtime or size change. Use cache.files=auto-full instead. (default: false)
- async_read: deprecated - Perform reads asynchronously. Use async_read=true instead.
- sync_read: deprecated - Perform reads synchronously. Use async_read=false instead.

**To Reproduce**

Read the Readme :)

**Expected behavior**

It would be good to know since which version of mergerfs the options are deprecated.

**System information:**

N/A

**Additional context**

N/A

**Comment by trapexit** [comment]
What's the issue precisely? I don't want people concerning themselves about versions as I want them to use the latest always. The mentioning of those options at all is just so that people know not to use them as found in old random blog posts.

**Comment by tig987** [comment]
I am using the version that comes with Debian buster distro, which is 2.24.2
It's not an issue, but I thought it would be good to know in which version an option disappeared.

**Comment by trapexit** [comment]
They haven't disappeared. They are just deprecated. I couldn't remove them without breaking most of the existing installs. In retrospect calling them deprecated is pointless due to that fact. I'm simply moving to an entirely new config system in the next major version.

BTW... 2.24.2 was released over 3 years ago. https://github.com/trapexit/mergerfs/releases/tag/2.24.2

Nothing wrong with using it but a lot has changed both in terms of mergerfs and the kernel features.
