### ISSUE TITLE
Threshold / Tolerance with eplus

### ISSUE THREAD

**Issue by Crowley007** [trapexit/mergerfs#958]
I like the path preserving policy and have disks of different sizes and find that eplus balances things nicely. It does cause some suboptimal behavior though and I'm looking for advice with policy logic, if this could be solved with the existing policies.

I spin down my disks and would like to minimize unnecessary moving of files from one disk to another and spinning disks up when it can be avoided. 

So for example, I have **/pool/download** and **/pool/media** folders on every disk, and I download something, now I have **/pool/download/example/** on the disk with the least used space. Next it gets moved/renamed to **/pool/media/example/**, however more often than not, the disk with the least used space has changed at this point and **"example"** gets copied to another disk. 

I would like to avoid this while still keeping the path preservation, moving the **"example"** within the same disk. Of course there could be the case that **/pool/media/example/** already exists on another disk and files get added to **/pool/media/example/dir1** etc. in which case copying to that disk is what I want. I only want to keep the example on one disk after all.

Hopefully my attempt at explaining what I want makes sense, could it be done?

**Comment by trapexit** [comment]
Sorry but I'm not following. You have to describe the desired behavior in terms of filesystem functions. The existing behavior is described in detail in the docs: https://github.com/trapexit/mergerfs#rename--link

Preserving paths, strictly, by definition requires the behavior as defined. Otherwise it isn't preserving paths. I'm not sure what other behaviors are possible.

**Comment by trapexit** [comment]
>I spin down my disks and would like to minimize unnecessary moving of files from one disk to another and spinning disks up when it can be avoided.

That's really not something you can be accomplish. mergerfs *must* request data from disks to make decisions. That will typically lead to the OS spinning up the drive if the data isn't cached.

**Comment by trapexit** [comment]
>Next it gets moved/renamed 

We have to be precise in our terms. There is no such thing as "move". There is "rename", "link", and "open, read/write loop to copy data, metadata read/write, close". When discussing behavior of a filesystem and what mergerfs does you must speak about the low level requests made by software. No the high level concepts that the client software present you.

**Comment by Crowley007** [comment]
So the main problem for me is that "least used space" is the best option to keep data somewhat balanced across different sized disks but when the balance is close the disk that gets used for create changes often and even when adding just one new file since the download folder is different than the final location. 

I'm not 100% sure, but it seems to me that if the difference in used space between disks is large enough, the download is created and renamed on the same disk and then there is no unnecessary spin up of a second disk.

I guess I'm asking if I can get the desired result with the existing policies, when I download something create and keep it on the same disk even if it goes against least used space momentarily, unless there is an existing path on another disk where the file should end up.

Sorry if my explanation does not make sense, don't think I can explain it any better.

Perhaps it would require something that does not exist, "fill this disk until used space difference is larger than x, then change to the next disk with least used space".


I do use cache.files=auto-full, any other cache settings that would be useful in trying to reduce unnecessary spin up of disks?

**Comment by trapexit** [comment]
>I'm not 100% sure, but it seems to me that if the difference in used space between disks is large enough, the download is created and renamed on the same disk and then there is no unnecessary spin up of a second disk.

You are incorrect. How does mergerfs even know the information relevant to make that decision? By reading from the filesystems which in tern, if not cached by the OS, will require it to spin up.

>I guess I'm asking if I can get the desired result with the existing policies, when I download something create and keep it on the same disk even if it goes against least used space momentarily, unless there is an existing path on another disk where the file should end up.

Same disk as what? You have to describe the problem as a time series of events and functions. When a create file request is made it runs the policy and then calls `create` on the filesystem the policy returned. What change to the policy are you proposing? eplus by definition will choose the drive with the least used space of the directories which exist for the target file's request. How would you make it different? 

I don't really follow what you mean by "fill this disk until space diff is larger than X". That would ladder requests as soon as that threshold was filled. Would it not? You would simply bounce between drives. Filling one drive at a time similar to now. And how do you determine that? What makes it continue to choose a single branch? Timeout? It still has to query the underlying system for information to make decisions. What *exactly* are you trying to accomplish here with this behavior. If it is minimizing the spinning of disks I assure you that is a failed strategy. mergerfs is not and can not be written in a way that removes querying of underlying devices in a typical setup. It is best to control what interacts with mergerfs itself.

>I do use cache.files=auto-full, any other cache settings that would be useful in trying to reduce unnecessary spin up of disks?

All of them? By definition if something isn't cached it must be requested. Nothing is actively cached though so unless the information is already requested it must be. And naturally the caching level depends on available ram and kernel behaviors mostly.

**Comment by Crowley007** [comment]
Yes, the least amount spinning disks possible is the end goal. If that's not possible, ok. Perhaps drive pooling is not the right solution for me.

But right now the policy is not really filling up one at a time, because least used space keeps changing. Example:

Disk1: used space 100GB
Disk 2: used Space 101 GB

I download a 5gb file, it gets created on Disk1. Now it gets renamed to a different path and since Disk1 now has 105GB it gets copied to Disk2.  This is the problem I was trying to solve.

**Comment by trapexit** [comment]
The only way to not have drives spin up is to not use them. mergerfs, RAID, and any other aggregation technology by necessity will have to use more than one drive to make certain decisions. If it was so easy to just cache all relevant data so as to not use the drive the OS would be doing it because it would make things faster. It can't predict the future so it can only cache *after* the first request.

To *limit* (not stop) spinup in a meaningful way mergerfs would have to assume no changes out of bound (which for some users is common) and then use an SSD or RAM if you had enough to cache literally *all* of the filesystems under it minus the data itself. And given that common software like plex and whatnot will open files to read metadata that's not going to fully stop spinups anyway. And even then it was found years ago that even asking the OS if a disk was spun down could spin up certain devices. So you'd have to be able to completely blacklist those devices. It's non-trivial.

>I download a 5gb file, it gets created on Disk1. Now it gets renamed to a different path and since Disk1 now has 105GB it gets copied to Disk2. This is the problem I was trying to solve.

I doubt that's happening. mergerfs doesn't turn `rename` requests into file copies and the client app does not know anything about what mergerfs is doing. Read the link about `rename`. If you are using `lus` policy then it will 100% of the time do the rename on the same device. It doesn't make any sense to do otherwise. A `rename` can *only* happen on the same device. If you aren't using path preservation policy then it clones the path if necessary and calls `rename`. If that fails that is what is returned to the app. That error wouldn't be EXDEV. Almost all apps will error out if rename fails with anything but EXDEV. In which case it would do a copy. If the file is being copied it is unlikely it is due to mergerfs as you've described it.

**Comment by Crowley007** [comment]
I use eplus for create and see that file copy happening all the time when the final destination subdirectory does not exist.  If it's a problem with the software and not mergerfs, well the end result is still the same.

Of course  if the second disk spins up every time anyway,  it's just a minor annoyance and solving that would not solve the main issue of spin up.

On that topic, I have pretty successfully limited my linux server of spinning up disks, I use for HD-idle for spin down and to check drive status, using OS functions to check mostly results in spin up as you say. 

But I guess this is a problem I can't solve with mergerfs, so the question is answered.

**Comment by trapexit** [comment]
>I use eplus for create and see that file copy happening all the time when the final destination subdirectory does not exist. If it's a problem with the software and not mergerfs, well the end result is still the same.

I was describing the situation in relation to lus. Which gives you the behavior your talking about and assumed you would have tried. Or ignorepponrename. If you use eplus and the target path doesn't exist then it will return EXDEV as you've requested it to do. You can't have it both ways. There is no way to preserve paths and not preserve them at the same time. If you want renames to always succeed then you can't use path preservation. At best you can turn it off for renames which kinda defeats the purpose because over time it would negate the path preservation.

Regardless the other drive will spin up anyway when mergerfs has to do all the rename calculations. Unless *all* the data requested is cached by the OS.

>On that topic, I have pretty successfully limited my linux server of spinning up disks, I use for HD-idle for spin down and to check drive status, using OS functions to check mostly results in spin up as you say.

Right. Years ago I literally rewrote all of mergerfs to cache all metadata to an SSD to prove out a request from people to spin down drives. I was asked to make it check the drives and only use the cache if the drive was spun down. Problem was that some drives spun up to answer the question totally negating the feature. Caching all the metadata fully destroyed the users' other usecases.

The best policy is to manage the software such that it doesn't use the devices. Or buy 2.5" drives where the noise and electricity usage is lower. Making sure all drive usage is centered around a certain time period and using SSD as a cache drive for downloads if you torrent or something is a more reliable setup than trying to engineer the filesystem to manage it. mergerfs can and does cache certain things that minimize requests to disk but things are more complex than people understand.

**Comment by Crowley007** [comment]
> I was describing the situation in relation to lus. Which gives you the behavior your talking about and assumed you would have tried. Or ignorepponrename. If you use eplus and the target path doesn't exist then it will return EXDEV as you've requested it to do. You can't have it both ways. There is no way to preserve paths and not preserve them at the same time. If you want renames to always succeed then you can't use path preservation. At best you can turn it off for renames which kinda defeats the purpose because over time it would negate the path preservation.
> 

Yes, this was and has been the problem all the time. I have used ignorepponrename and it will break the path preservation so it's a no go.   

So I was really asking for a policy that does not exist, not sure if it even could. 

I'm not constantly adding files, so my dream policy would use drive 1 for create and when the difference of used space between drive 1 and 2 goes over a configured threshold, then start filling disk2.  Something like that would limit the unnecessary copying considerably. I would configure the threshold so that the average single download would not cause the least used space to change disks.

But that's just a quick idea to solve the problem without thinking whatever problems it could cause, and again does nothing for the bigger goal of less spinning disks.

**Comment by trapexit** [comment]
I'm still not fully following. If you have path preservation enabled then those decisions can only be made *after* that list of targets is filtered by the path. Unless you're claiming it should turn on and off the "ep" part based on the size gap? Which would seem to me to be the same as not using it at all in relation to the path preservation part of things. Minimizing entropy is a losing game in my opinion. "ep" policies are generally for very specific usecases. Most people are better off with mfs, lus, or msp* versions.

I'm happy to add new policies but they have to be carefully designed. What are the inputs of the decision, the algo, and it must output a set of branches. f(x) = y.  And it has to be understood in how it will behave over time. Not simply in a single execution.

And correct... you're talking marginal differences wrt spinning disks. A rename is less work than a copy so it would be less likely to cause drives to spin or keep spinning longer but to what degree is highly dependent on the situation at hand. The client software behavior. Which is something I can't predict.

**Comment by Crowley007** [comment]
Spinning disks is the reason I use path preservation as well and works also when reading files, only the disks needed will be spun up most of the time. If I'm reading files, in my use cases, I mostly read files from the same directories in a session so having the files spread across multiple disks is something I'm trying to avoid.

I was under the impression that the problem is the "lus" part not "ep" since when the file gets moved to the final location the original download drive does not have least space anymore. That is what I think should be turned off or have a tolerance of some sort.. Unless I'm totally mistaken what causes the behavior.

I have no idea about the filesystem functions so I can't say how the policy would really work, just thinking out loud. But still this is what I would ideally have:


Disk1: used space 100GB
Disk 2: used Space 101 GB

I download a 5gb file, it gets created on Disk1 in /pool/download/example, and then moved to /pool/media/example, still on disk1. If it is newly created folder use the same disk.  But if /pool/media/example exists already on disk2, then use that.

**Comment by Crowley007** [comment]
I think I follow but just to be sure, is there no policy combination that would create the folder on disk1 so that the rename would succeed but use the same drive that originally had "least used space", disk1?

**Comment by trapexit** [comment]
Wait sorry... after rereading your last line I'm not sure I understand. "If it is newly created folder use the same disk. But if /pool/media/example exists already on disk2, then use that."

There is never a situation where there isn't an existing folder. It is a requirement for a folder to exist before any function can be called to use it. Not in a way that is compatible with how anything works normally.

`rename(filepathA,filepathB)`

If either path doesn't exist then it must return ENOENT error. I'm not even sure the kernel would make a request to mergerfs unless it knows the path exists. I'd have to test it. Even if it did... software isn't written to work like that because it would never work normally. A rename requires existing targets. `mkdir` would have to happen first and there is no way to correlate a previous mkdir with a future rename.

**Comment by Crowley007** [comment]
Ok this is getting confusing again :).

```
Disk 1: used space 100GB
Disk 2: used space 101 GB

I download a 5gb file, it gets created on Disk1 in /pool/download/example, and then moved to /pool/media/example, still on disk1. If it is newly created folder use the same disk. But if /pool/media/example exists already on disk2, then use that.
```

In this example, the /pool/download is on every drive, /pool/media is on every drive.  /pool/media/example does not exist (yet).

I use eplus, so Disk1 is used for downloading "example". Now after the download finishes, the folder /pool/download/example gets renamed (?) to -> /pool/media/example. 

As it stands now, this pretty consistently gets created on disk2. I would want it to be created on disk1. 

UNLESS disk2 already hat /media/example

**Comment by trapexit** [comment]
I don't know how to explain it any other way than as in the docs which is a step by step of the process.

You are claiming that all directories are already everywhere. So 1) there is nothing to "preserve". There is no filtering due to lack of paths on a branch. So as the docs explain a rename would succeed.  The fact /media/example exists on disk2 is irrelevant except that it would be deleted after the successful rename.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/blob/2.32.6/src/fuse_rename.cpp#L231

You can see here... if using path preserving it only tries to rename on the source.

rename(disk1/download/example,disk1/media/example)

If that fails it tries to see if a create would result in "disk1/media" being created and if so will just create it and rename. That's just a shortcut. You are claiming that this fails and so the client software copies the file over to disk2. Which can only happen if disk1 does NOT have /media (or you aren't describing your situation accurately and are using bind mounts or something).

**Comment by Crowley007** [comment]
Yeah, i guess I can't articulate this correctly but one last attempt:

All directories are not everywhere, "example" does not exist, it's a newly created download. 

 /pool/media/ exists everywhere /pool/download exists everywhere  /pool/media/example does not exists, it needs to be created as a result of a finished download and rename(?). 

I would want /pool/media/example to be created to the same disk that was used for download as a result of eplus, it had the least used space before download. But after download the same disk does not have the least free space anymore and /pool/media/example gets created to the disk that has. ie Disk2.  That causes an extra copy operation that is not needed in my opinion.

**Comment by trapexit** [comment]
You have to be very very explicit. When I say in the docs I need literally *all* information I'm not exaggerating. It was/is not clear if "example" is a file or directory. You don't have a trailing '/' which tends to imply a file. Also... we have to know exactly what the software is doing. Is it calling rename on the directory or the files in the directory. This is a complicated dance and leaving out *anything* will confuse its understanding.

As mentioned... if rename(/pool/download/example,/pool/media/example) is the call made then there is no way it copies. Not unless they aren't the same mount which you've not indicated is the case. "eplus" means nothing here. Reread the link I provided. The "create" policy has nothing to do with the initial rename attempt. It only matters if rename fails. And according to what you've described there is no way for it to fail with EXDEV.

**Comment by Crowley007** [comment]
After some investigating, I believe the software creates a new "example" directory and just moves/renames the contents from download/example/ to the media/example/.

But this information doesn't really get me any closer to a solution. Thanks for trying to help though.

**Comment by trapexit** [comment]
In that case I'm not sure what could be done. The mkdir is a random independent event. If it then does a rename from `/pool/download/example/foo` to `/pool/media/example/foo` and `mkdir(.../foo)` landed on disk2 then... 🤷‍♂️ /example doesn't exist on disk1 so it has to return EXDEV. You'd have to predict the future and not make /example on disk2. The only thing I could think of is use ignorepponrename=true which as described ignores path preservation on rename requests and then it would copy /example to disk1 and then rename. But it would still have to query disk2 to get the info on /example to copy. So you would remove the copy but not the possible spinup. At best I could have a feature that tries to clean up directories but that feels weird and where would it stop? Till unlinks/rmdirs fail due to them being in use?

**Comment by Crowley007** [comment]
Yeah, at least I understand the underlying problem better now, I'm starting to think there really is no good solve for this. Thanks again.
