### ISSUE TITLE
Is there a way to get default linux next-file behavior?

### ISSUE THREAD

**Issue by quarz12** [trapexit/mergerfs#986]
On my normal drives when i open a file (specifically an image) i can, (if the program allows it) use mouse wheel or arrow keys to go to the next filein the folder.
On the mergerfs drive this does not work.
Is there an option to enable this feature?

**Comment by trapexit** [comment]
I'm sorry but I've no idea what you're referring to or how this has to do with mergerfs.

**Comment by trapexit** [comment]
I don't understand what you mean "appears to be blocked or not implemented by mergerfs"

mergerfs has no relation to irfanview. That program isn't even a Linux app. mergerfs doesn't run on Windows.

**Comment by quarz12** [comment]
irfanview was just an example, every image viewer has this option. I assume the program cant see what other files are in the folder. since it works on any other disk it appears to me that it has to have something to do with how mergerfs emulates the drive or an option that is blocking it

**Comment by trapexit** [comment]
>I assume the program cant see what other files are in the folder.

That's simply not possible if you're saying the app is opening the files and seeing a list of them in file explorer or wherever you're listing these files. Again, mergerfs isn't even what that app is interacting with directly. It is interacting with SMB I'm guessing. 

You really should be talking with the author of these programs you say are acting weird because only they can say why they don't work as you expect.
