### ISSUE TITLE
Drive Spin Up Behaviour

### ISSUE THREAD

**Issue by oregonpillow** [trapexit/mergerfs#988]
Hi,

At the moment i have a setup like this:

`/mnt/disk1 + /mnt/disk2 + /mnt/disk3 --> /mnt/media`
where all 3 disks have 2 folders in: movies & tv  , meaning the pooled drive also has these --> `/mnt/media/movies` + `/mnt/media/tv`

The problem is, if i `cd /mnt/media` then ALL the 3 disks will start spinning up from sleep, presumably because all 3 of those drives contains folders movies & tv.

Is this correct / expected behavior? If so, i'm probably against using mergerFS as awesome as it is, because i don't want all 3 drives to kick up just because 1 of them is accessed....

However, i'm curious if instead a _specific_ file is opened e.g. `/mnt/media/movies/<file>.mkv` then becauase it's _specific_, it would surely only cause the respective specific drive to spin up? Is my thinking correct?

**Comment by trapexit** [comment]
> The problem is, if i cd /mnt/media then ALL the 3 disks will start spinning up from sleep, presumably because all 3 of those drives contains folders movies & tv.

Because the only way to know what is on a filesystem is to ask. Asking, unless the kernel has all that data cached (often unlikely), will cause it to need to spin up.

>Is this correct / expected behavior? 

Yes.

> If so, i'm probably against using mergerFS as awesome as it is, because i don't want all 3 drives to kick up just because 1 of them is accessed....

How do you propose doing otherwise? I've discussed this with people for several years and except for treating the system as almost read only, caching all metadata and storing it in RAM, and ensuring processes like PLEX and others that will sometimes read files for metadata are not running, I don't see a solution.

> However, i'm curious if instead a specific file is opened e.g. /mnt/media/movies/<file>.mkv then becauase it's specific, it would surely only cause the respective specific drive to spin up? Is my thinking correct?

No. mergerfs is a dumb proxy. It doesn't own or control the underlying filesystems.

You can:
1) scan everything up front and store that all in RAM and hope nothing changes out of band in which case you could target specific filesystems
2) cache previous lookups and future requests can target the specific branch but if the value has timed out or some random request fails with ENOENT suggesting it was there and was removed or moved then do a full scan and try again
3) just do as it does now and the docs about policies suggest and scan each time

1 uses a lot of memory on and if you do *anything* that is active (like torrent or download files, which most people do) then it isn't really worth doing outside some slight perf improvements doing lookups. And for spinup on systems where you only occasionally access filesystems... certain apps will still cause spinup due to opening files. And it can't be used if filesystems are changed out of band because there isn't a practical way to know changes were made so it would just not know about changes until something triggered another scan.
2 doesn't help with spinup because it caches on demand 

Limiting spinup is not trivial in the best of cases. It has been accomplished only on systems with very little activity using block level caches like bcache and making sure the software used doesn't do anything but read standard metadata (stat, readdir)

**Comment by oregonpillow** [comment]
Thanks for your reply @trapexit . Very helpful, I really appreciate it....mmm i'll think some more on it. It would be nice to use but maybe not necessary for my use case. The drives would only be spun up when media is accessed. And since myself and friends accessing media files is very sporadic, it would cause a lot of drive sleeps/spin ups each day which is more wear and tear on drive headers than i'm comfortable with.

 Do you know of any other similar solutions which don't act as "dumb proxies" and would only spin up the needed drive?

**Comment by trapexit** [comment]
You have to define your usage pattern thoroughly to understand whether or not the drive will spin up. This is non-trivial to accomplish. Asking some drives if they are asleep causes them to wake up. All existing caching systems are on demand because it just isn't a common usecase otherwise. I spent many hours adding a caching layer years ago for this very purpose and it didn't work because the users in question had a number of apps that would open files to check / update metadata. The best you could do is have a mostly read only system or at least nothing changing out of band and precalculate all locations for files so you don't have to search for them. Scanning all my drives takes several minutes at least.

Filenames can be upwards of 4096 bytes in total length. If you have 1 million files (i have nearly 3) that is 4GB possible RAM usage just for the names. Then you have to add data structure overhead and per file metadata. Probably another GB or so at least. That's a decent amount of memory. It could be stored on disk but then you're doing all that IO to do more IO which isn't really great. And it won't work if you do anything out of band which many people do.

The best way to limit spinup is to not cause it in the first place. The second is to use block caching like bcache or maybe what zfs does and have it configured to keep metadata on the cache drive.

**Comment by oregonpillow** [comment]
Thanks. I've already tested with my current drives (whose sole purpose is to store media files); they only spin up when data is read from the media serving application. They don't spin up for anything else that the system currently does. This is only made possible because I have other drives for things which get accessed frequently. (e.g downloading / seeding / automation stuff). Since I know how my drives work, and i know they will be 100% asleep except when i want to stream a video on them, then it makes sense for me not to merge them. The other benefits of merging are not essential to me, although nice.

**Comment by trapexit** [comment]
Yeah. As I mentioned the best policy is to not trigger the request rather than try to figure out how to make the request not read the drive. Plex and other media player platforms allow you to add multiple paths per library and unless you have a bunch of random drives you can pretty easily just configure the software to combine the data. You can also trivially use mergerfs for writes if you want to spread "automatically" across drives. Write to the mergerfs pool, read from the individual drives.

**Comment by oregonpillow** [comment]
@trapexit thanks for your suggestions. I like your suggestion: I think this would be the best use case for my needs and desires; minimizing all-drive spin ups and still benefiting from "auto" managed writes for "writing" apps like radarr etc.
Thanks a lot!
